### ISSUE TITLE
requirements.txt에 불충분한 패키지 추가

### ISSUE THREAD

**Issue by HeoSeungBeen** [oss2024hnu/coursegraph-py#10]
기존 코드를 로컬에서 실행시키기 위해서는

해당 컴퓨터에 python, yaml, matplotlib, networkx 의 라이브러리를 설치해야 합니다.

도커 컨테이너를 활용해 컨테이너 내부에서 코드가 동작하게 하여, 개발 환경 세팅의 부담을 줄여야합니다

**Comment by kyahnu** [comment]
@HeoSeungBeen 이 이슈는 일단 라이브러리 설치로만 제한합시다. 한꺼번에 두 개의 이슈를 올리는 셈이 되니까요.

그리고 도커 컨테이너를 어떻게 만들지 방향도 좀더 구체적으로 제시할 필요가 있으니까 어떻게 할지는 추후에 별도의 이슈로 조금만 더 자세히 올려주세요.

**Comment by kyahnu** [comment]
> 해당 컴퓨터에 python, yaml, matplotlib, networkx 의 라이브러리를 설치해야 합니다.

이 부분에서 python은 공식 파이썬 배포를 설치하면 기본적으로 파이썬 인터프리터가 설치되면 자동으로 설치되는 파이썬 기본라이브러리에 해당하기 때문에 굳이 명시할 필요가 없을 것 같고요

yaml라이브러리가 한개가 아니라 여러개가 있을테니까 그중에서 어떤 이름의 패키지를 설치해야 되는지 명확히 해서

requiremets.txt에 반영하는 것으로 풀리퀘스트를 작성하면 될 것 같습니다.

**Comment by HeoSeungBeen** [comment]
확인했습니다

**Comment by kyahnu** [comment]
@HeoSeungBeen PR들어와서 승인한 코드에 StrictYAML로 이미 변경되어 main브랜치에 반영되어 있으니까 PR 작성할 때 그냥 기본 yaml 패키지 이름이 아닌 strictyaml로 하면 될 것 같네요

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/11 이걸로 처리 완료
