### ISSUE TITLE
과목과 관련된 자격증 또는 트랙과 관련된 자격증 추가

### ISSUE THREAD

**Issue by ppoppy** [oss2024hnu/coursegraph-py#101]
과목과 관련된 자격증을 데이터에 추가하여 그래프에서 추가로 보여주고,
트랙을 선택해 관련된 자격증을 보여주면 좋을 것 같습니다.

**Comment by kyahnu** [comment]
자격증은 과목이수체계도와 별도로 다루어야 하는 내용으로 이번 프로젝트의 범위는 아닙니다.

**Comment by kyahnu** [comment]
주제를 벗어나는 이슈이므로 반려하고 닫습니다.
