### ISSUE TITLE
과 선택

### ISSUE THREAD

**Issue by ppoppy** [oss2024hnu/coursegraph-py#103]
과 별로 데이터 파일이 있으므로, 과를 사용자가 선택하여 원하는 과의 결과물을 볼 수 있으면 좋을 것 같습니다.

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/issues/50 와 중복 제발 지금까지 어떤 이슈들이 있는지 파악을 하고 이슈를 올립시다
