### ISSUE TITLE
선수과목 관통문제가 있습니다.

### ISSUE THREAD

**Issue by SiRyung** [oss2024hnu/coursegraph-py#105]
수학을 선수과목으로 지정하는 과목에 역사가 없음에도 불구하고
물리학과 컴퓨터과학을 가르키기 위해 간선이 노드위를 관통하는
문제가 있습니다.

추가적으로 #97 의 가로 세로의 축을 바꾸는 아이디어가 매우 훌륭하다고 판단하여
그 코드까지 더불어 PR하였습니다.

**Comment by kyahnu** [comment]
가로세로축은 바꾸지 않기로 했습니다. 이미 다른 이슈에서 논의했습니다.
인터넷에 과목이수체계도를 검색해 보시면 가로 형식이 훨씬 많습니다.
가로세로축은 바꾸지 말아주세요.

관통 문제도 이미 다른 이슈에서 논의되고 있습니다. 중복 이슈를 발생시키지 말아주세요
