### ISSUE TITLE
코드를 테스트하는 함수가 필요하다고 생각합니다

### ISSUE THREAD

**Issue by qusk** [oss2024hnu/coursegraph-py#108]
pytest나 doctest 등의 모듈을 이용해 테스트 함수를 만들어 코드 실행 전 테스트를 하면 오류가 어디서 발생 했는지
찾기도 쉽고 무슨 오류인지 한번에 알아 볼 수 있기 때문에 있으면 좋겠다고 생각합니다

**Comment by kyahnu** [comment]
테스트에 대한 이슈를 아무도 제시하지 않아서 일단 점수로 포함하는데요
조금 더 구체적인 방안을 제시해 주면 좋겠습니다

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/226 이슈를 올린 사람이 말한 도구는 유닛테스트라서 정확히는 이 PR과 관련이 내용상으로 있는 건 아니지만 이거 올린 사람도 유닛테스트만을 고래해서 이슈를 올린 시점상 그렇지 않을 가 같아서 이걸로 해결된 것으로 보고 일단 이 이슈는 닫습니다. 나중에 진짜로 유닛테스트가 필요한 사이즈의 모듈이 생기면 그때 또 누가 새로 올리면 될 일이고
