### ISSUE TITLE
이수체계도 보기 쉽게 개선하기 위한 방법

### ISSUE THREAD

**Issue by ohnakyu** [oss2024hnu/coursegraph-py#115]
사용자가 특정 부분을 확대하거나 축소하여 세부 정보를 살펴볼 수 있는 기능을 추가하면 좋을 것 같습니다.

**Comment by kyahnu** [comment]
기본 show에서도 제공하는 거 아닌가요 화면 키우거나 해서. 그리고 어차피 이미지 만들어내는 기능도 추가하는 이슈가 이미 있어서 이미지 파일로 저장되면 대부분의 이미지 뷰어에서 확대 기능이 있습니다. 그래서 이건 지금 cli유틸리티에서는 좀 맥락이 맞지 않는 제안이므로 반려합니다. 혹시 gui 데이터를 만들고 싶은건가요?

**Comment by kyahnu** [comment]
그래서 이 이슈는 빈려하고 닫습니다
