### ISSUE TITLE
yaml 기본 형태에 따른 정의된 스키마 설정

### ISSUE THREAD

**Issue by JWhyeok** [oss2024hnu/coursegraph-py#117]
현재 ce.yaml의 트랙, 마이크로디그리 key 에 velue 가 없는 과목들이 있습니다.
velue가 없는 key는 삭제하는것이 알맞은 형식이라고 생각합니다. 수정 부탁드립니다.

**Comment by JWhyeok** [comment]
리스트를 이용해 이 이슈를 해결한 것 같습니다. 이제 value 에 공백이 있어도 유효성 검사에 통과하도록 코드를 수정하겠습니다.

**Comment by kyahnu** [comment]
해결되었다니 그럼 닫겠습니다
