### ISSUE TITLE
파일을 읽을 때 예외처리가 필요할 것 같습니다.

### ISSUE THREAD

**Issue by jangjuntae** [oss2024hnu/coursegraph-py#12]
예외처리를 해주지 않으면 파일이 빈 파일이거나 파싱중 오류가 일어났을 때를 처리하지 못합니다.

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/14 이걸로 처리 완료

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/14 이걸로 처리 완료된 줄 알았으나 ...

예외처리를 했으면 함수를 부른 다음 뭔가 하지 말거나 해야 되는데 그낭 정상 진행함
에러메시지가 콘솔에 출력은 되긴 하겠지만
그 다음으로도 정상 진행되고 빈 하얀 화면만 보이는 상태로 프로그램이 계속 실행됨

보통 예외처리한 다음에는
- 에러 메시지는 stderr로 뿌림
- 정상 흐름으로 회복 가능하면 회복 가능한 단계를 밟아 회생
- 정상 흐름으로 회복 불가능하면 프로그램은 sys.exit(1)과 같이 0이 아닌 종료코드로 처리

이런 식으로 하는 게 좋기 때문에 개선을 위해 이슈를 다시 열었습니다

**Comment by jangjuntae** [comment]
import sys를 추가하고 오류가 났을때 강제 종료하는 코드를 추가했습니다

**Comment by kyahnu** [comment]
> import sys를 추가하고 오류가 났을때 강제 종료하는 코드를 추가했습니다

@jangjuntae pull request 아직 안올라왔던데요, 올리는 중인가요?

**Comment by jangjuntae** [comment]
요청 넣었습니다

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/21 여기서 해결 다시 이슈 close 합니다
