### ISSUE TITLE
중복 코드를 최소화 해야 합니다.

### ISSUE THREAD

**Issue by eongeung** [oss2024hnu/coursegraph-py#13]
adjust_coordinates 함수에서 위치를 초기화하고 갱신하는 부분이 중복된 것 같아서, 한번 재구성 해보았습니다.

def adjust_coordinates(subjects):
    adjusted_pos = defaultdict(list)
    for subject in subjects:
        pos_key = (subject['학년'], subject['학기'])
        adjusted_pos[pos_key].append(len(adjusted_pos[pos_key]) * 0.4 - ((len(adjusted_pos[pos_key]) - 1) / 2) * 0.4)
    return adjusted_pos

**Comment by kyahnu** [comment]
minor 리팩토링은 별도의 이슈 없이 pull reqest를 넣어주시면 됩니다. 위와 같이 작성하면 코드 들여쓰기도 안 되어 있고 내용을 알아보기 힘듭니다. markdown 사용법을 확인하고 활용하면 좋습니다.

**Comment by kyagrd** [comment]
minor 리팩토링을 별도의 이슈 주제로 점수를 부여하기는 곤란하고, 본인이 직접 PR을 넣으면 그에 대한 점수는 적용하겠습니다.

그렇다고 코드의 기능은 유지한 채 구성을 바꾸는 리팩토링이 전부 다 점수를 받지 못하는 이슈거리가는 건 아니고, 프로젝트가 더 진행되면서 함수나 아니면 사용자 정의 데이터 구조 등이 많아지거나 할 때 이걸 좀 큰 단위로 개선하는 필요성이 보일 때 그걸 정리해서 해결하는 방향을 잡아주는 리팩토링 이슈라면 점수로 반영하겠습니다.

왜 이렇게 하나면 if문 하나 고치고 while문을 for문으로 고치고 이런 걸 하나하나 점수를 위한 이슈를 너무 자잘하게 만들어내면 프로젝트 운영에 오히려 병목이 될 거 같아서요.

**Comment by eongeung** [comment]
넵 pr로 넣겠습니다.

**Comment by kyahnu** [comment]
PR도 오류가 나기 때문에 이 이슈는 이제 그만 닫겠습니다. 테스트는 해보고 PR 요청 바랍니다
