### ISSUE TITLE
커리큘럼 교과목의 변동사항을 알 수 있도록 하는게 좋을거같습니다

### ISSUE THREAD

**Issue by Wonsoox** [oss2024hnu/coursegraph-py#130]
학과의 커리큘럼이 바뀌거나 수정되거나, 과목이 대체되는 경우, 기존과목의 수업이수 권장학년이 내려가는 경우가 있습니다. 따라서 그래프를 만들면 연도별로 커리큘럼의 상태를 저장하고 로그형식으로 남겨서, ~년도 커리큘럼 1,2,3학년과 같은 형식으로 사용자가 쉽게 확인할 수 있도록 만들어야 합니다.

**Comment by kyahnu** [comment]
이런 기능은 아이디어는 좋은데 한학기 안에 이렇게 많은 사람이 함께 진행하는 방식으로는 구현하기가 쉽지 않을 것 같습니다.

특정 년도에 대한 내용이라도 제대로 보여주는 유용한 동작을 하게 만드는 것만 해도 상당히 높은 목표라고 생각이 되기 때문에요.

이제는 한 주 이내로 입력 yaml에 포함될 내용과 형식에 대한 것은 확정을 해야 합니다. 

계속 이걸 늘려 나가서는 코드 작성이 스케줄상 이걸 도저히 따라갈 수 없게 됩니다. 

지금으로서는 21년도 입학생 기준 커리큘럼, 22년도 입학생 기준 커리큘럼, 23년도 입학생 기준 커리큘럼 각각에 대한 yaml 파일을 따로 따로 만들어서 활용할 수 있는 프로그램을 만드는 정도로까지만 한정합시다.

**Comment by kyahnu** [comment]
이후로는 yaml의 형식을 확장하는 이슈는 받지 않습니다. 일정상으로도 그렇고 다듬어서 정리할 단계라서요.
