### ISSUE TITLE
show_yaml.py에서 fonts 변수에 <list index out of range> 에러가 뜨는 현상

### ISSUE THREAD

**Issue by HkKIMHNU** [oss2024hnu/coursegraph-py#139]
윈도우 기준 fontutil.py Ln21 Col40 부분 'Malgun' 을 현재 시스템에 설치되어 있는 폰트이름 혹은 'Malgun Gothic' (맑은고딕 malgun.ttf) 으로 변경하면 해결됩니다

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/tree/a5f9482e78e2f89626ee317577a04669483c4fa0 이 버전 기준을 이미 해결된 이슈입니다.
