### ISSUE TITLE
main.py 파일에서 -s 명령어가 실행이 안됩니다.

### ISSUE THREAD

**Issue by lunatic280** [oss2024hnu/coursegraph-py#141]
현재 파일에서 class로 만들어진 부분이 삭제되어 실행이 안됩니다.

**Comment by kyahnu** [comment]
어떻게 테스트하면 어떤 오류가 나는지 상세한 정보와 함께 이슈를 작성 바랍니다

**Comment by lunatic280** [comment]
#128로 업데이트 되었을때 main.py에서 
python __main__.py -s 를 실행시키면
<module>
    from show_yaml import ShowYaml
ImportError: cannot import name 'ShowYaml' from 'show_yaml'
오류가 나왔습니다.
현재는 이 오류가 해결되었습니다.
