### ISSUE TITLE
__main__.py안의 parser파트 모듈화

### ISSUE THREAD

**Issue by Wonsoox** [oss2024hnu/coursegraph-py#143]
__main__.py안에 있는 CLI를 위한 parser부분을 따로 파일로 모듈화시켜서 main안을 좀더 깨끗히 정리하는것이 좀더 좋을거 같다고 생각합니다.

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/issues/125 와 겹치는 내용입니다. 여기서 같이 논의합시다.
