### ISSUE TITLE
show_yaml.py 의 모듈을 사용하고 있지 않습니다.

### ISSUE THREAD

**Issue by SiRyung** [oss2024hnu/coursegraph-py#149]
기존 클래스 수정 및 퇴화한 코드가 이미 수정되어
아직 반영되진 않았지만 #145 의 코드에 작성하였습니다.

하지만 #145 코드 역시 font_util.py의 모듈을 불러와서 사용하는 것이 아닌
이름이 동일한 함수를 재정의해서 만들어서 사용하였기에
모듈에서 불러와서 폰트를 찾고 그려낼 수 있도록 코드를 수정하여야 합니다.

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/150 로 수정됨
