### ISSUE TITLE
__main__.py가 비정상적으로 프로그램이 종료될 때 로그를 출력했으면 좋겠습니다.

### ISSUE THREAD

**Issue by tkdgns08523** [oss2024hnu/coursegraph-py#154]
오류가 나면 오류가 어떻게 하다가 났는지 바로 알기엔 어려움이 있어서 로그를 이용해 찾으면 좀 더 수월할 것 같습니다.

**Comment by kyahnu** [comment]
pdb를 활용하면 되지 않나요?

**Comment by kyahnu** [comment]
디버거 활용하면 해결되는 문제죠? 닫습니다.

**Comment by kyahnu** [comment]
이 이슈는 반려합니다. 사실 이미 중복된 이슈에요. 이미 비슷한 거 올렸다 반려된 이슈가 있습니다. 과거 closed된 이슈들까지 확인한 후 새로운 이슈를 올려주세요.
