### ISSUE TITLE
노드 텍스트가 노드의 경계를 벗어나는 문제

### ISSUE THREAD

**Issue by lunatic280** [oss2024hnu/coursegraph-py#16]
과목 이수 체계도를 그리는 과정에서 '컴퓨터과학' 텍스트가 노드 밖을 빠져나가는 문제가 발생하고 있습니다.
만약 노드의 경계보다 텍스트가 큰 경우 글자 크기를 줄였으면 좋겠습니다.

**Comment by JWhyeok** [comment]
concept-demo.py 노드를 그리는 부분인 
nx.draw(G, pos, with_labels=True, node_size=2000, node_color="skyblue",  font_family=font_name, font_size=10, font_weight="bold") 에서 node_size와 font_size 수정이 가능합니다 !
제가 테스트 했을떄  node_size = 1500, font_size = 8 이 적당했습니다.

**Comment by kyahnu** [comment]
@lunatic280 off-topic이긴 한데 초대 수락 아직 안했으면 초대 수락해주세요

**Comment by kyagrd** [comment]
제 생각에 일단 이 이슈는 나중에 가면 해결이 필요해지긴 할 거 같습니다.
실제 학과 전공과목 이름 중에는 다섯글자보다 더 긴 과목도 있어서 ...

그렇게 되면 아마 원형보다는 직사각형이나 이런 모양이 노드 모양으로 더 어울릴 것 같기도 하고요
너무 긴 과목 이름은 중간에 줄바꿈을 해서 한줄이 아니라 두 줄에 나눠 표시되도록 한다던가 한다던가
등으로 개선해는 방법이 있겠네요


그래서 저장소에 실제 학과 데이터를 추가하는 이슈와 PR이 진행이 되어서 실제 데이터도 올라오고 나서
실제 좀더 긴 이름을 포함한 과목이 있는 입력 파일로 이 이슈에 대한 본격적인 작업을 해도 되고요

아니면 이 이슈를 당장 해결하려면 컴퓨터개론 말고 한 열글자쯤 되는 과목을 현재 input.yaml 하나 더 추가하거나 테스트를 해가면서 진행하는 방법도 있겠고요
