### ISSUE TITLE
노드 생성 처리

### ISSUE THREAD

**Issue by HeoSeungBeen** [oss2024hnu/coursegraph-py#161]
ai-concept-demo 내부의 concept-demo.py 의 노드 생은 겹치는 등의 문제가 발생했습니다.

main.py 의 노드생성의 경우 이런 일을 방지하고자 학년과 학기를 통해 좌표를 설정하고 노드를 생성하는 과정이 필요해보입니다.

다른 코드와 마찬가지로 모듈화 해서 깔끔하게 확인 할 수 있도록 해야합니다

**Comment by kyagrd** [comment]
중복되는 이슈입니다 반려합니다. 기존에 올라온 이슈와 겹치는 내용을 작성하지 말아주세요
