### ISSUE TITLE
많은 머지로 인해 yaml의 위치가 올바르지 않게 수정된 것 같습니다.

### ISSUE THREAD

**Issue by ppoppy** [oss2024hnu/coursegraph-py#164]
테스트를 위해 concept-demo.py를 실행해 본 결과 yaml 파일을 찾지 못합니다.

**Comment by kyagrd** [comment]
concept-demo에는 더 이상 코드를 반영하지 않을 예정입니다.

**Comment by kyagrd** [comment]
그래서 이 이슈는 반려합니다.
