### ISSUE TITLE
글꼴을 프로젝트에 포함하지 말고 설치된 글꼴을 이용합시다

### ISSUE THREAD

**Issue by kyagrd** [oss2024hnu/coursegraph-py#17]
[5e4fd5c299d53f1636a1b1cd89a3e534e9b83ff4](https://github.com/oss2024hnu/coursegraph-py/tree/5e4fd5c299d53f1636a1b1cd89a3e534e9b83ff4) 버전 기준으로 현재는 ttf 글꼴 파일을 프로젝트에 포함시키고 있는데 이건 생각해보니 좋은 방식이 아닙니다

지원하는 OS를 리눅스, 맥, 윈도우즈 이 세 가지로만 잡고
윈도우즈의 맑은고딕
맥의 애플고딕 (요즘 맥기본 한글 글꼴이 뭐죠? 서울체인가 그건가요?)
리눅스에서 보통 한글 쓰려면 설치하는 나눔고딕
보통 이러니까

나눔고딕, 맑은고딕, 애플고딕(아니면 요즘 바뀌었으면 서울체나 뭐 그런 걸로 하나 정해서)

이렇게 시스템 설치 폰트를 쿼리해서 세 가지 폰트 중 하나 있으면 그걸로 쓰고 없으면 그냥 에러를 내고 종료하는 걸로 처리합시다.

왜 이렇게 해야 되냐면 지금처럼 별도 디렉토리에 ttf를 놓고 운영체제에 폰트를 설치를 안해 놓은 상태 파이썬 실행 중에만 임시로 활용하는 거는 show()로 어찌어찌 보이게는 되지만, 어차피 시스템 폰트가 없으면 확인한 결과를 이미지나 PDF 등으로 변환해서 저장한 다음 저장된 결과 파일을 활용하려 할 때 시스템에 설치된 외부 이미지 뷰어로 볼 때 글자들이 보이지 않고 깨지는 경우가 생기게 됩니다.

그러니까 별도로 이런 유틸리티 프로그램에 폰트 사본을 들고다니는 거는 좋지 않은 거 같습니다.
그냥 우리가 실행하려는 프로그램이 한글 폰트 셋 중 하나에 의존성이 있다는 걸 분명히 명시하면 됩니다.
마치 matplotlib 라이브러리를 우리가 여기에 복사본 압축해서 우리 저장소에 별도로 저장하지 않듯이요

**Comment by kyagrd** [comment]
font_manager의  findSystemFonts()라던가 fontManager.ttflist 라던가 그런걸로 시스템에 설치된 폰트 중에서 있으면 그걸로, 없으면 에러를 내면 될 듯 합니다

**Comment by JWhyeok** [comment]
시스템 확인 후 폰트를 지정하는 함수를 추가해 pull request 했습니다!

**Comment by kyahnu** [comment]
> 시스템 확인 후 폰트를 지정하는 함수를 추가해 pull request 했습니다!

https://github.com/oss2024hnu/coursegraph-py/pull/27 이걸로 대부분의 기본설정으로 설치된 OS 배포판에서는 돌아갈텐데  findSystemFonts()나 fontManager.ttflist를 활용하는 것이 이식성이 더 좋습니다. 운영체제를 기본설정 말고 폰트 디렉토리를 다른 곳으로 설정해서 쓴다거나 하는 설정 변경도 운영체제에서 얼마든지 가능하기 때문에

그래서 이 이슈는 일부 해결되었지만 개선의 여기자 있어 추가 개선에 대한 PR도 가능하기에 계속 열어는 놓겠습니다.

**Comment by kyahnu** [comment]
이후 관련 내용 구현은 lib/fontutil.py 에서 진행합시다

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/73 으로 이제 해결된 것으로 보고 일단은 닫습니다
