### ISSUE TITLE
ai-concept 안의 폰트를 밖으로 빼야 합니다.

### ISSUE THREAD

**Issue by eongeung** [oss2024hnu/coursegraph-py#171]
cooursegraph-py에 폰트체가 없고 aiconcept 버전 안에 있는 data 폴더 안에 있기 때문에 이 폴더 안의 폰트를 밖으로 빼내야 합니다.

**Comment by kyagrd** [comment]
예전에 논의된 이슈인데요, 과거 이슈를 확인해 주세요. 폰트는 설치된 것을 쓰기로 했습니다. 워드프로세서나 일러스트레이터 같은 무슨 문서 편집이나 출판용 응용프로그램이 아닌 이상 일반적인 유틸리티에 폰트를 포함하는 것 자체가 일반적으로 잘못된 접근방법입니다.

**Comment by kyagrd** [comment]
말 나온 김에 아예 폰트를 제거해 버려야겠네요 저장소에서

**Comment by eongeung** [comment]
교수님 그럼 혹시 여기에 있는 폰트 경로들을 삭제해서 pr시켜도 되나요?
예를 들어 fontutil.py 에서 이런 문구if fprop.get_name() == 'NanumGothic': 입니다. 이것 때문에 실행이 안돼서 여쭤봅니다.
