### ISSUE TITLE
show_yaml에서만 실행됩니다.

### ISSUE THREAD

**Issue by eongeung** [oss2024hnu/coursegraph-py#182]
show_yaml에서만 실행시키지 말고, main함수로 불러와서 실행시켜야 합니다.

**Comment by kyagrd** [comment]
사실 show_yaml 에서만 실행시키는 코드가 있어도 됩니다. 지금 작성하고 있는 모든 기능을 `__main__.py`와 연결시키려는 것은 아닙니다.

제가 설계도를 정확히 무슨무슨 기능을 만들고 그 이외에는 만들지 말라고 던져주고 하는 게 아니기 때문에

main에는 최소한의 기능만 포함시키고 필요하다면 예를 들어 GUI라던가 이런 기능들은 오히려 별도의 파일을 통해 실행시키려는 방향으로 생각하고 있거든요. 그래서 이 이슈는 지금 프로젝트 진행방향과 반대되는 거라서 반려합니다.
