### ISSUE TITLE
readme에 main함수에는 최소한의 기능만 포함시켜야 된다는 말을 추가해야합니다.

### ISSUE THREAD

**Issue by eongeung** [oss2024hnu/coursegraph-py#183]
main함수에 수정할 수 있기 때문에, GUI 같은 기능은 gui.py와 show_yaml.py 파일에서 수정할 수 있도록 해야된다는 사실을 추가해야합니다.

**Comment by kyahnu** [comment]
이거 처리했습니다.

**Comment by kyahnu** [comment]
네 참고로 최근 커밋에서 show_yaml.py 의 이름이 show_table.py 로 바뀌었습니다
