### ISSUE TITLE
show_yaml 실행시 나오는 그리드가 잘리거나 가독성이 좋지 못합니다

### ISSUE THREAD

**Issue by HkKIMHNU** [oss2024hnu/coursegraph-py#186]
![스크린샷 2024-05-08 220328](https://github.com/oss2024hnu/coursegraph-py/assets/162100013/0725ac8e-b75e-49c4-8ed7-352f20a95c88)
![스크린샷 2024-05-08 215528](https://github.com/oss2024hnu/coursegraph-py/assets/162100013/ed91f020-8e2e-4220-a0e4-fd6f74c0e940)

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/219 로 해결된 것으로 보임
