### ISSUE TITLE
#166 #167 index of range가 난다는 issues와 PR은 문제가 있습니다.

### ISSUE THREAD

**Issue by SiRyung** [oss2024hnu/coursegraph-py#189]
#166 #167 에서 제가 PR한 파일에서 Index of range에러가 난다고 하였는데 이는 잘못된 제출입니다.
해당 코드에서 시스템에서 폰트 파일을 가져오는 것은
map형식의 딕셔너리 기능에서 폰트이름, 폰트파일 경로 등을 통해 폰트 경로를 불러오는 방식이었습니다.

167에서 말하시는 것은 딕셔너리 폰트파일경로 인덱스 1값이 Null이기에 Index of range에러가 발생한다는 것인데
윈도우 xp는 너무 구 OS이기에 제외하고, 윈도우 7과 8, 10, 11에서는 윈도우를 설치할시 기본적으로
malgun gothic의 굵음, 기본, 기울임 3개가 제공됩니다. 윈도우 설치시 폰트파일을 설정하지 않았을 경우에
3개가 깔리기에 Index of range가 발생할 수 없습니다.
 또한 설정을 했더라도 폰트 파일의 경로가 try, except를 통해 예외처리를 해야할 부분이지
index값을 바꾸는 PR은 올바르지 않습니다.

**Comment by kyahnu** [comment]
현재대로 해도 문제가 없고 혹시 특이한 환경에서 1개만 리스트에 걸리는 경우도 잘 동작하는 지금 index 0을 유지하기로 합시다.

**Comment by kyahnu** [comment]
1이 혹시 안되는 경우에 예외처리를 하면 된다는 언급을 빼놓고 이해했네요 다시 이슈 엽니다.

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/192 로 해결
