### ISSUE TITLE
pr을 할 때 자세히 적어줘야 된다는 점을 onbording 디렉토리에 문서화

### ISSUE THREAD

**Issue by eongeung** [oss2024hnu/coursegraph-py#190]
pr을 하고 한 두줄만 적어서 내면 처음 보는 사람은 모를 수 있기 때문에, 어떤 부분이 수정되고 또 어떤 부분이 수정됐는지 정확하고 최대한 상세히 적어줘야된다는 내용을 readme에 추가해야합니다.

**Comment by stayineverywhere** [comment]
#196 으로 README.md 에  추가하였습니다.

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/214 이걸로 해결
