### ISSUE TITLE
이슈를 만들때 상세하게 적어야 한다는 것을 README 에 추가하여야 합니다. 

### ISSUE THREAD

**Issue by stayineverywhere** [oss2024hnu/coursegraph-py#191]
예를 들어 코드 수정하는 이슈를 만들때 이전 코드는 이러한 점의 불편함이 있어 이렇게 수정하는 것이 좋을 것 같습니다 등의 형식으로 제공하는 것을 추가하면 좋을것 같습니다.

**Comment by stayineverywhere** [comment]
#196 으로 README.md에 추가하였습니다.

**Comment by kyagrd** [comment]
이것은 README에 하지 말고 온보딩 디렉토리에 새로운 파일로 추가해 주세요
