### ISSUE TITLE
show_graph.py의 테스트 방법

### ISSUE THREAD

**Issue by JWhyeok** [oss2024hnu/coursegraph-py#194]
[2e59ad1](https://github.com/oss2024hnu/coursegraph-py/commit/2e59ad1fca6728fefeffc4deba120788a0a28998) 이 버젼의 
show_graph.py 의 경우 데이터파일의 경로를 직접 변경하며 실행 여부를확인해야합니다. 따라서 show_graph.py 내부에서도 따로 파일을 입력받아 실행 될 수 있도록 추가해야할 것 같습니다.

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-py/issues/197 이거랑 중복된 내용이고 이미 해결
