### ISSUE TITLE
__main__.py 에서 -f 옵션을 table로 실행시켰을 때, 파일의 이름을 한 번더 입력하는 문제

### ISSUE THREAD

**Issue by ppoppy** [oss2024hnu/coursegraph-py#197]
![image](https://github.com/oss2024hnu/coursegraph-py/assets/127175733/7d5fc3f2-826c-4f2b-9576-3838106df480)
위에서 data/ce.yaml을 입력했음에도 아래에서 한번 더 ce를 입력해야 합니다.
yaml 파일의 이름을 한 번만 입력되도록 바꾸어야 합니다.

**Comment by kyagrd** [comment]
버전 언급 안했으므로 가산점은 없습니다

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/211 로 해결
