### ISSUE TITLE
테이블을 출력하면 명령어를 수정해야 할 것 같습니다.

### ISSUE THREAD

**Issue by lunatic280** [oss2024hnu/coursegraph-py#198]
예를 들어 python coursegraph -f table -i data/ai.yaml 입력하면 ai.yaml파일이 실행되는 것이 아니라 파일을 선택하라고 나옵니다.
여기서 다른 파일을 선택하고 실행시키면 다른 파일의 테이블을 실행되고 있습니다.  처음에 입력한 명령어로 파일을 다시 입력하지 않고 실행되게 해야 할 것 같습니다.

**Comment by kyagrd** [comment]
중복입니다 반려

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-py/issues/197 와 중복입니다 반려
