### ISSUE TITLE
파일 인코딩 오류

### ISSUE THREAD

**Issue by JWhyeok** [oss2024hnu/coursegraph-py#2]
https://github.com/oss2024hnu/coursegraph-py/commit/07929e5dc7c1adba432e0ecc4977b70b0a293849 버전 기준으로

ai-concept-demo를 실행해 보면 아래와 같은 오류 메시지와 함꼐 프로그램 실행이 되지 않습니다.

파이썬에서 파일을 읽을시 발생하는 인코딩 오류같습니다.

UnicodeDecodeError: 'cp949' codec can't decode byte 0xed in position 12: illegal multibyte sequence

**Comment by JWhyeok** [comment]
인코딩 방식이 수정된 파일을 request 해뒀습니다!

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/3 머지했습니다
