### ISSUE TITLE
마이크로 디그리 공식 명칭으로 쓰는 것이 필요합니다. 

### ISSUE THREAD

**Issue by sominoh** [oss2024hnu/coursegraph-py#201]
실제공식명칭과 다릅니다.

**Comment by kyagrd** [comment]
이런 식으로 어떤 부분이 문제인지 실제 사례를 들어서 어디인지 구체적으로 지적 없이 무성의하게 올리는 이슈는 앞으로는 점수를 인정하지 않을 예정입니다.
