### ISSUE TITLE
AI 학과 yaml 파일의 과목명을 공식명칭으로 바꿔야 합니다. 

### ISSUE THREAD

**Issue by stayineverywhere** [oss2024hnu/coursegraph-py#203]
ai.yaml 에 있는 과목명을 한남대학교 ai융합학과 편람에 있는 공식명칭으로 바꿔야 합니다. 
예로 딥러닝기초이론 (DNN) 을 딥러닝심화이론(MD) 와 같이 수정하여야 합니다.

**Comment by eongeung** [comment]
#205
