### ISSUE TITLE
#108 데이터 처리에 관한 테스트 함수가 필요할거 같습니다.

### ISSUE THREAD

**Issue by hy2oning** [oss2024hnu/coursegraph-py#209]
#108 데이터 처리 로직이 정확하게 수행되는지 확인하기 위해  처리하고 변환하는 로직, 예를 들어 과목 데이터를 특정 형식으로 변환하거나, 요구 사항에 맞게 필터링하는 기능이 필요하다고 생각합니다.
필터링: 특정 조건 (예: 특정 학년 및 학기의 과목만 추출)에 맞게 데이터가 필터링되는지.
데이터 변환: 데이터 항목이 요구 사항에 따라 적절히 변환되는지.

**Comment by kyagrd** [comment]
우리가 지금 만들고 있는 yaml을 그래프나 이미 필요한 정보를 적절히 추출해서 보여주고 있고, 테이블은 전체 정보를 다 보여주고 있는데요.
필터링하는 기능은 무엇을 위해 필요하죠? 필요한 이슈인지 의문이라 일단 반려하고 닫습니다.

지금 일반적인 데이터베이스를 만들려는 게 아니라 전체적으로 모든 과목 교과과정을 시각화하려는 것이 목표인 프로젝트입니다.
