### ISSUE TITLE
다전공생의 필수과목 표시 추가

### ISSUE THREAD

**Issue by Rayakeem** [oss2024hnu/coursegraph-py#216]
ce.yaml 파일을 수정하여 본전공생과 상이한 다전공생의 필수 과목을 표시할 수 있도록 수정하면 좋을 것 같습니다.

또한 show_graph.py 파일을 수정하여, 과목 노드를 표시할 때 본전공생과 다전공생의 필수 과목을 색상 또는 라벨로 구분할 수 있도록 기능을 개선하면 좋을 것 같습니다.

**Comment by kyagrd** [comment]
이거 학기중 프로젝트 진행 일정상 계속 스펙이 추가되면 코드 작성이 따라기 추가 스펙 안받는다고 공지했는데요. 반려합니다.
하이클래스나 이 프로젝트 안의 문서 등에 공지된 내용을 한번씩 확인해 주세요.
