### ISSUE TITLE
ce.yaml에서 마이크로디그리가 공식명칭으로 수정되지 않았습니다.

### ISSUE THREAD

**Issue by KimDongYeun** [oss2024hnu/coursegraph-py#222]
#202이슈와 #206 PR을 확인해보니
트랙만 수정된 것 같습니다. yaml 구조에서 트랙, 마이크로디그리, 과목명을 공식명칭으로 지정하였기에 추가적인 수정이 필요할 것 같습니다.

**Comment by kyahnu** [comment]
사실 이 이슈는 트랙 이슈를 보면 그거와 거의 유사한 이슈라고 볼 수 있어서 (실제로 전에 올라온 이슈가 있는데 설명이 좀 너무 없어서 반려하기도 해서 ...) 하여간 사실상 중복 이슈로 보고 PR에만 점수를 부여하겠습니다.
