### ISSUE TITLE
ce.yaml 공식명칭 지정에 따른 스키마 변경사항

### ISSUE THREAD

**Issue by KimDongYeun** [oss2024hnu/coursegraph-py#225]
0039e1a45c61814e1866f2510922e028c812d8cd를 기준으로
ce.yaml 마이크로디그리에 webapp이 공식명칭인 웹/앱개발자로 수정되었습니다. #224 
따라서 yamlSchema.txt와 schema_checker.py에 특수문자 '/'를 허용하도록 수정이 필요해보입니다.
현재 특수문자는 '_' 와 '.' 만 사용 가능하도록 정의되어 있습니다.

**Comment by kyahnu** [comment]
아직 이 이슈를 닫지 않는 이유는 다른 학과 보니까 &도 과목명, 트랙, 마이크로디그리 이름으로 가능하더라고요. 이것도 추가해야 할 거 같네요.
