### ISSUE TITLE
학년, 학기 별로 과목이 구분이 되어서 표현이 되면 좋을 것 같습니다.

### ISSUE THREAD

**Issue by jangjuntae** [oss2024hnu/coursegraph-py#23]
정의역 치역을 표현하는 것처럼 아래와 같이 표현을 하면 구분이 쉽고 선행 과목의 표현이 좀 더 직관적으로 표현이 될 것 같습니다.

아래는 예시입니다.
https://m.blog.naver.com/mathclass1/221967869896

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-py/issues/15 와 중복된 이슈입니다.

중복된 이슈인지 내용을 확인하고 올려주세요. close된 이슈 중에도 혹시 중복이 있을 수 있으니 closed 된것도 이슈 올리기 전에 살펴보고요.

**Comment by jangjuntae** [comment]
감사합니다
