### ISSUE TITLE
#22와 같은 문제를 해결하기 위해 비교할 수 있는 파일을 하나 더 만들어도 좋을 것 같습니다.

### ISSUE THREAD

**Issue by SiRyung** [oss2024hnu/coursegraph-py#235]
![학년별 배경 구분](https://github.com/oss2024hnu/coursegraph-py/assets/91623756/7d4e7cfc-d1aa-48fc-bbc6-194b59d1b08e)
위 사진은 input.yaml파일을 기반으로 출력한 그림입니다.

![분석불가](https://github.com/oss2024hnu/coursegraph-py/assets/91623756/227edef0-f6d0-4dd6-ba92-d60d5d21f2d0)
위 사진은 me, ce, ai 등의 yaml파일의 데이터들을 불러왔을때의 그림입니다.

보다시피 위는 아무 문제가 없고, 아래는 읽기에 너무 불편한 점이 많습니다.
하지만 위 문제를 적당히 중화시킨 test.yaml파일이 하나 더 있다면 비교하기 쉬울 것 같아 제가 한번 넣어봤습니다.

![간편화](https://github.com/oss2024hnu/coursegraph-py/assets/91623756/571767cd-3cb2-4bdc-a746-a9aac4ae8a3b)
위 그림은 4개 이상부터 노드간의 침범이 일어남을 쉽게 알 수 있으면서도 간편하여 보기가 쉽습니다.

input.yaml파일에 데이터를 더 넣어서 비교하면 되지 않냐는 의견이 있을까봐 그러는데
input.yaml파일에는 학점/강의/실습 부터 선수과목까지 입력하여야기 때문에 나중에 추가하고 뺐다하는 과정이 번거롭습니다.
간편화된 파일과 기존 파일 두개를 두고 비교하면서 간편화된 파일에 데이터를 추가/삭제하여 보기 쉽게 만드는 편이 더 좋을 것 이라고 생각했습니다.

추후 프로젝트 마무리시 제거하면 되겠습니다.

**Comment by kyahnu** [comment]
이게 지금 겹침방지를 가로 좌표를 조절해서 해결하려는 게 애초에 문제라서
세로 좌표로 조절해서 해결하는 걸로 아마 좀있으면 누군가 PR을 하긴 할 거 같습니다. (아직 안하고 있더라도 지금 이렇게 논의를 하면 누군가는 PR 거리구나 하고 달려가서 시작할지도요)
사실 1학기에 한 학과의 전공과목이 아무리 많아도 5개나 6개 이상은 잘 열리지 않으니까 가로로 옆으로 빽빽해서 생기는 문제는 금방 해소될 문제인 거 같기는 해요

**Comment by kyahnu** [comment]
학년별로 배경색을 다르게 한 거는 확실히 알아보기 좋네요

**Comment by kyahnu** [comment]
PR 이슈에 이중 가산점은 애매하니 가산점은 하나만 할께요 알아보기 좋게 이미지까지 친절하게 잘 첨부해 줘서 알아보기 좋았습니다.
