### ISSUE TITLE
-그래프작업- 노드 크기 수정시 폰트도 비율에 맞게 크기를 변화시키는 작업이 필요합니다

### ISSUE THREAD

**Issue by Wonsoox** [oss2024hnu/coursegraph-py#236]
![로드맵](https://github.com/oss2024hnu/coursegraph-py/assets/162536366/1d8e6afa-867a-49eb-a381-c9048bf1b318)
기존 코드를 보면 노드와 폰트 크기가 분리되어 있습니다. 노드와 폰트의 크기는 아무런 상관관계도 없기에 화면상에서 노드 바깥으로 폰트가 빠져나오는 불상사를 맞게 됩니다.
![test](https://github.com/oss2024hnu/coursegraph-py/assets/162536366/092183cb-2882-4a73-9b8c-c61ea3dee5e4)
 또한 이후에 있을 그래프 환경 개선작업에서 폰트와 노드의 크기를 각각 만져줘야 하는 불편함이 있을뿐아니라, 노드안에 들어가는 폰트의 크기값을 또 구해야한다는 단점이 있습니다.

ex)  귀찮은 일 반복
노드 사이즈 10
폰트사이즈 5
결과 : 폰트 삐져나옴
노드 사이즈 10
폰트사이즈 1
결과 : 뭐야 너무 작잖아...
노드 사이즈 10
폰트사이즈 8
결과 : 이번엔 삐져나왔네...
이후 반복..

**Comment by Wonsoox** [comment]
#16 에서 이와 비슷한 이슈를 확인하였지만, 값을 고정적으로 줄이는것과, 비율에 맞춰서 줄이는 것은 다르다고 생각하여 이슈를 올리게 되었습니다

불완전한점 : 여전히 긴글자에 대해서는 무방비 상태입니다

**Comment by kyahnu** [comment]
이정도면 사실상 중복된 이슈이므로 반려합니다. 관련이 있는 이슈는 따로 지나치게 가지를 치지 말고 해당 이슈에서 같이 논의해 주세요.

**Comment by kyahnu** [comment]
아 이거 pt px와 관련된 또 다른 이슈군요 잘못 이해서 반려했는데 다시 엽니다

**Comment by kyahnu** [comment]
> #16 에서 이와 비슷한 이슈를 확인하였지만, 값을 고정적으로 줄이는것과, 비율에 맞춰서 변화하는 것은 다르다고 생각하여 이슈를 올리게 되었습니다
> 
> 불완전한점 : 여전히 긴글자에 대해서는 무방비 상태입니다

긴 과목명은 두줄로 표시하던가 뭔가 다른 방법을 찾아야 할 듯 합니다. 폰트 비율 조절과 별도의 이슈로요

**Comment by kyahnu** [comment]
코드를 이미지로 캡춰해서 작성하지 말고 텍스트로 작성을 합시다

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/237 로 해결
