### ISSUE TITLE
schema_checker.py  함수 def validate_yaml(file_path) 에서 입력값 검증 강화 

### ISSUE THREAD

**Issue by stayineverywhere** [oss2024hnu/coursegraph-py#238]
현재 함수 def validate_string_or_sequence(value): 에서는 re.match(r'^[A-Za-z가-힣\w.]+$', item) 와 같은 코드를 사용하고 있습니다. 이는 [A-Za-z가-힣\w.] 는 알파벳, 한글, 숫자, 밑줄(_), 마침표(`.``)를 포함한 문자열 그리고 +: 앞의 패턴이 최소 한 번 이상 반복되어야 함을 나타냅니다.  즉 알파벳 , 한글 , 숫자 , 밑줄 , 마침표를 포함한 문자열이 아닌 경우에는 에러가 발생하게끔 합니다. 

하지만 숫자를 입력할때 실수로 음수를 입력할 수도 있기에 def validate_yaml(file_path) 함수 안에 try 문에 
- 학년이 음수일 경우에 에러가 발생한다는 코드를 추가하면 좋을것 같습니다.  

실수로 제가 음수인 값을 입력하였는데 학년이 음수여도 에러가 발생하지 않고 코드가 계속 진행이 되더라구요. 하지만 학년은 음수일수가 없으니 '학년이 음수인 경우에는 학년은 음수일 수 없습니다. ' 라는 에러를 발생시키면 어떨까 의견을 제시합니다.

**Comment by stayineverywhere** [comment]
따라서 def validate_yaml(file_path): 함수 안에서 for index, subject in enumerate(data["과목"], start=1):  코드 밑에 있는 try 코드에서 f subject["학년"] < 0:  raise ValueError("학년은 음수일 수 없습니다.") 라는 코드를 추가적으로 삽입하면 어떨까요??

**Comment by kyahnu** [comment]
아니면 아예 딱 1,2,3,4,5,6로 제한하는 것도 좋고요. 대부분 4년제고 건축인가 뭐 그런 쪽 5년제인가 6년제까지만 있을 거고 우리학교에 그 이상은 없는 걸로 알고 있으니까요.

**Comment by stayineverywhere** [comment]
#245 로 수정하였습니다!
