### ISSUE TITLE
gui 라이브러리로 tkinter 대신 PyQt5를 사용하는것이 더 좋을 것 같습니다.

### ISSUE THREAD

**Issue by JWhyeok** [oss2024hnu/coursegraph-py#239]
tkinter는 python 에 내장되어있는 gui 라이브러리 이지만 이것은 간단한 gui를 만들때 사용하는것이 좋다고 알고있습니다.
여러 사람들이 참여하는 만큼 이 프로젝트는 꽤나 규모가 큰 프로젝트라고 생각되어 PyQt5 를 사용하여 GUI 기능을 제작하는것이 좋을 것 같습니다.

![pyqtedit](https://github.com/oss2024hnu/coursegraph-py/assets/162516396/58d1a7c5-df63-46c6-9334-d556a644deef)

이 사진은 PyQt5에서 제공하는 GUI designer 입니다.
위젯을 간단한 클릭으로 생성하고 조작이 용이하기에 이 라이브러리를 추천합니다.

하단 링크는 PyPI 사이트의 PyQt5 최신버젼 링크입니다.

https://pypi.org/project/PyQt5/

PyQt5 설치 명령어 :

- pip install PyQt5

PyQt5 에서 제공하는 tool 설치 명령어:

- pip install pyqt5-tools

PyQt5 와 tool 을 전부 다운받으면 현재 파이썬이 설치되어있는 폴더로 들어간 후

\Lib\site-packages\qt5_applications\Qt\bin
폴더에 들어가면 designer.exe 실행파일이 있습니다. 실행파일 실행시 위에 있는 사진과 같은 GUI 에디터가 실행됩니다.

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/240 로 해결
