### ISSUE TITLE
다중 선수 과목이 있을 시 화살표의 애매한 경우

### ISSUE THREAD

**Issue by peyoon** [oss2024hnu/coursegraph-py#24]
예를 들어 컴퓨터과학 노드를 가리키는 경우 선수 과목으로 물리학과 수학이 있습니다.
이 때 현재 수학 -> 물리학 -> 컴퓨터과학 이렇게 화살표가 가리키고 있는데
현재 컴퓨터과학을 가리키는 화살표는 물리학 노드에서 출발하는 화살표 하나 입니다.
수학이 컴퓨터 과학의 선수 과목인지 명확하게 알기 어렵다는 점에서 애매한 점이 있어 이슈로 올립니다.

**Comment by kyagrd** [comment]
이것은 이슈가 아닌 걸로 보고 닫겠습니다.
기본적으로 사람이 머리속에서 transitive하게 생각해야지, 이걸 전부 다 표시하면 가장 기초적인 과목에서 나가는 화살표가 너무 많아져서 오히려 그림이 복잡해집니다.
