### ISSUE TITLE
show_table.py 문서에 대한 가독성에 대한 코드 간결화

### ISSUE THREAD

**Issue by tkdgns08523** [oss2024hnu/coursegraph-py#241]
현재  5db3120 버전의 show_table.py 파일에서 21번 ~ 31번까지의 줄을 더 간결하게 하여 코드의 가독성을 높이면 어떨까 합니다.
![스크린샷 2024-05-10 191820](https://github.com/oss2024hnu/coursegraph-py/assets/162093089/2104359f-2e12-44de-8a61-b265e7b99ee6)

원래의 방식인 이 코드에서 ↑

![스크린샷 2024-05-10 191831](https://github.com/oss2024hnu/coursegraph-py/assets/162093089/89f13aa6-64bb-477d-b34a-0288db3054cf)

이 코드로요 ↑
코드를 간결화하여 차후에 코드가 늘어남에도 가독성에 더 수월하게끔 하는 것이 어떨까 합니다.

**Comment by SiRyung** [comment]
기존 3개에서 지정된 폰트파일
windows 3개, mac 4개, linux 5개 만큼을 돌려보니 무조건 3개에서 찾는 것보다는 좋을 것 같습니다.

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/242 로 해결됨
