### ISSUE TITLE
필요 패키지 확인 후 자동설치 시스템

### ISSUE THREAD

**Issue by JWhyeok** [oss2024hnu/coursegraph-py#25]
앞으로 다양한 기능이 추가되고 필요한 패키지가 많아질수록 패키지를 보유한 패키지를 확인하는 작업이 번거롭게 느껴질수도 있을것 같습니다. 그래서 사용하는 패키지를 확인하고 필요한 패키지를 자동으로 설치/업데이트 해주는 시스템을 만들면 좋을것 같습니다

**Comment by kyagrd** [comment]
requiremets.txt가 그겁니다.

이미 requirements.txt를 작성하고 있으니 이건 이슈거리가 아닌 것 같습니다.

참고자료:
https://code-angie.tistory.com/15
