### ISSUE TITLE
__main__.py 에서 try 문에 -f table 옵션에 오류의 가능성 줄이기

### ISSUE THREAD

**Issue by stayineverywhere** [oss2024hnu/coursegraph-py#252]
현재 __main__.py 코드의 def main():  try: 문 안에 있는 elif 문은 다음과 같습니다. 
- elif output_format=='table':
        data_processor = ShowTable(not show_mode, input_file, output_file)
        data_processor.process_data()

하지만 이는 -f table 옵션을 실행하였을 때 입력 파일이나 출력 파일의 존재 여부를 확인하지 않은 채로 실행됩니다. 
프로그램이 오류 없이 실행되기는 하지만 이는 예상과 다른 결과를 출력할 수도 있으므로 입력 파일을 지정하는 코드를 삽입하면 좋을 것 같습니다. 

현재 코드는 ShowTable 클래스가 입력 파일을 요구하지 않고도 인스턴스화되고 데이터 처리 메서드가 호출될 수 있기 때문에, 이 과정에서 입력 파일이 없는 경우를 처리하는 코드가 없다면 오류가 발생할 가능성이 있습니다. 

그러므로 elif 문에  if not input_file: 이라는 코드를 삽입함으로써 오류를 줄이는 것이 좋을 것 같습니다.

**Comment by kyahnu** [comment]
출력 파일의 존재 여부는 확인하지 않기로 하겠습니다. 그런 복잡한 기능들은 Makefile 같은 걸 활용하는 make 유틸리티로 하면 됩니다. 참고로 유닉스 유틸리티는 단순한 기능만을 최소화하여 작성하고 다른 기능을 하는 것은 다른 유틸리티나 쉘스크립트로 하는 것이 설계 철학입니다. 그래서 CLI 유틸리티는 그런 기능을 최소하하는 방향으로 진행하겠습니다.
