### ISSUE TITLE
__main__.py 에서 사용자 지정 사이즈 옵션 추가

### ISSUE THREAD

**Issue by stayineverywhere** [oss2024hnu/coursegraph-py#253]
main에 사용자가 출력 이미지의 크기를 지정할 수 있는 옵션이 있도록 코드가 수정되면 좋을 것 같습니다. 

현재 show_table 과 show_graph 에 figsize = (20,10) 과 같은 형태로 사이즈를 지정할 수 있게 되어 있는데 이는 show_graph 와 show_table에 동시에 똑같은 사이즈를 지정하고 싶을 때 번거롭습니다. 일일이 사이즈를 지정하는 함수를 찾아야 하기 때문입니다. 

따라서 main에 -s 옵션을 추가하여 show_table 과 show_graph에서 동시에 똑같은 사이즈의 크기로 이미지를 출력하고 싶을 때 사용하면 좋을 것 같습니다. 같은 사이즈로 출력하고 싶다면 figsize = image_size 이런 식으로 지정을 하도록 코드를 수정하면 좋을 것 같습니다. 

main은 그렇기에 parser.add_argument('-s', '--size', .... )  수정하여 # Accessing the command line options 에서 image_size = args.size 이런식으로 지정을 하면 show_table 과 show_graph 에서는 위에서 언급한 대로  figsize = image_size  이렇게 지정을 하면 동시에 같은 사이즈로 지정을 할 때 하나의 코드만 수정하면 되기에 편리할 것 같습니다.

**Comment by kyahnu** [comment]
생성되는 이미지 사이즈가 고정이 아니고 크기를 조절해서 생성하는 기능이 있었으면 좋겠다는 거는 취지는 이해가 가는데요

음 table과 graph는 지금 따로따로 실행을 시키기 때문에 현재 `__main__.py`의 CLI에서는요. 그래서 동시에 같은 사이즈로 하나만 지정한다는 게 어떤 경우를 말하는 건지는 정확히 모르겠습니다.

**Comment by stayineverywhere** [comment]
#301
