### ISSUE TITLE
show_table과 show_graph -o 옵션으로 출력 시 창을 띄울지 말지를 통일해야할것 같습니다.

### ISSUE THREAD

**Issue by kimjunseop716** [oss2024hnu/coursegraph-py#254]
현재 -f table -o out.png 로 테이블 생성 결과를 이미지로 저장하면 테이블 창이 열리고, 이미지가 저장이 되고 있습니다.
반면 -f graph -o out.png로 그래프를 생성하여 이미지로 저장하면 그래프 창은 열리지 않고, 이미지만 저장이 되는식으로 이미지로 결과를 확인하도록 되어있습니다. 그래서 이미지를 저장할 시에는 결과를 이미지로 확인하게 할 것인지, 아니면 이미지 저장과 창을 띄워 확인하게 할 것 인지를 통일하는게 좋을 것 같습니다. 제 생각에는 이미지 파일로 출력 결과를 확인할 수 있어서 굳이 창을 띄울 필요가 없다고 생각합니다.

**Comment by kyahnu** [comment]
창을 띄우지 않는 게 맞겠죠. 이미지로 저장하면 그 이미지 뷰어로 관찰하면 되니까요.

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/255 로 해결된 듯
