### ISSUE TITLE
Pull requests #255 에서 -i 옵션을 사용하지 않을 시와 -o 를 추가한 코드 수정 요청

### ISSUE THREAD

**Issue by stayineverywhere** [oss2024hnu/coursegraph-py#256]
현재 #255 에서 수정한 코드는 다음과 같은 형식입니다. 
-  try:
        if input_file:
            print(f"The input YAML file path has been specified: {input_file}")
        else:
            path = './data'
            files = os.listdir(path)
            print('선택 가능한 Yaml 파일 : ', end= "")
            for file in files:
                print(file, end= " ")
            print("")
            while(not input_file):
                input_file = input('파일 이름을 입력해주세요 : ')
                if input_file == '--exit':
                     1)return   -> sys.exit()         
                input_file = './data/'+os.path.splitext(input_file)[0]+'.yaml'
                if not os.path.isfile(input_file):
                    print('파일의 이름이 잘못되었거나 파일이 존재하지 않습니다.')
                 2)  input_file = False -> input_file = ''
            print(f"The input YAML file path has been specified: {input_file}")
           3) except: #예외 처리  -> except Exception as e : 
        parser.print_help(sys.stderr)
        raise Exception("Problem processing the input file")

**Comment by stayineverywhere** [comment]
즉 1) return 을 sys.exit()
2) input_file = False 를 input_file = ''
3) except : #예외처리 를 execpt Exception as e : 
로 수정하면 좋을 것 같습니다. 

그러면 입력 파일의 유무도 확인하면서 입력 파일이 정상적으로 제공될때까지 계속되게끔 수정하였습니다. 

#255 에서는 루프가 조건에 따라 끝나는 것이 아니라, 입력 파일이 없으면 루프가 계속되도록 설계되어 있기에 조건에 따라 끝나게끔 수정하였습니다.

**Comment by stayineverywhere** [comment]
즉 수정된 코드는 다음과 같습니다.
- try:
    if input_file:
        print(f"The input YAML file path has been specified: {input_file}")
    else:
        path = './data'
        files = os.listdir(path)
        print('Selectable YAML files: ', end="")
        for file in files:
            print(file, end=" ")
        print("")
        while not input_file:  # Correct the loop logic
            input_file = input('Please enter the file name: ')
            if input_file == '--exit':
                sys.exit()  # Use sys.exit() to exit the program
            input_file = './data/' + os.path.splitext(input_file)[0] + '.yaml'
            if not os.path.isfile(input_file):
                print('Invalid file name or file does not exist.')
                input_file = ''  # Reset input_file to continue the loop
        print(f"The input YAML file path has been specified: {input_file}")
except Exception as e:  # Catch specific exceptions
    parser.print_help(sys.stderr)
    raise Exception("Problem processing the input file:", str(e))

**Comment by kyahnu** [comment]
-i 옵션을 주지 않으면 아무것도 하지 말고 오류를 내며 종료하면서 --help 메시지를 stderr에 뿌려주면 충분할 거 같습니다.
파일 선택은 쉘에서 하는 걸로 코드를 단순화하는 게 관리하기도 좋고 인터페이스도 일관됩니다

**Comment by kyahnu** [comment]
-o 가 있을 때 창을 띄우지 말아야 하는 건 그렇게 하는 게 맞는 거 같네요. 이미지가 생성되면 이미지를 열어보면 되는데 별도로 또 미리 띄워줄 필요는 없죠

**Comment by kyahnu** [comment]
이슈에 직접 코드 수정 내용 적는 것은 보통 권장하지 않습니다.
토론할 필요가 있는 부분의 코드라면 모르겠는데
해결책 즉 PR을 작성하게 되면 PR에 코드 수정 내역을 깃헙에서 보여주는 기능이 이미 있기 때문에 ...

그리고 만약에 코드 일부를 발췌해서 작성할 거면 Markdown에서 코드 인용해서 적는 방식에 맞게 코드를 인용해서 작성해 주세요

**Comment by kyahnu** [comment]
이거는 입력 파일을 stdin 으로 받지 않는 것으로 이미 수정되었기 때문에 이 이슈는 무효한 거 같습니다.

https://github.com/oss2024hnu/coursegraph-py/issues/254 이 이슈와 유사한 이슈인데 이미 PR이 올라와서 이미 해결되었다고 봅니다.
