### ISSUE TITLE
어떤 기능도 수행하지 않고 있는 옵션 --verbose의 삭제 / 기능 부여에 관하여 건의합니다.

### ISSUE THREAD

**Issue by Nighthom** [oss2024hnu/coursegraph-py#257]
https://github.com/oss2024hnu/coursegraph-py/blob/main/coursegraph/__main__.py

__main__.py 내 --verbose 옵션은 현행 버전에서 "Verbose mode enabled." 라는 문자열을 출력하는 기능 외 어떠한 기능도 수행하지 않고 있습니다. 

__main__.py 내 27-31 라인
```python
    verbose_mode = args.verbose
    show_mode = False
    # Perform actions based on options
    if verbose_mode:
        print("Verbose mode enabled.")
```
사용하지 않을 옵션이라면 삭제할 것을, 아니라면 해당 옵션에 맞는 기능을 추가할 것을 건의합니다.

**Comment by kyahnu** [comment]
이거 그냥 인공지능이 작성해준 기본 틀이 있어서 남아있는 건데 지금으로선 관련 기능이 없어서 삭제하는 게 맞을 거 같네요
