### ISSUE TITLE
codespace에서 python coursegraph -i data/input.yaml -o out.png 실행 안됨

### ISSUE THREAD

**Issue by jangjuntae** [oss2024hnu/coursegraph-py#258]
5개 파일 전부 다 실행이 안되는 것 같습니다
오류 내용은 out of range입니다

**Comment by kyahnu** [comment]
어떤 버전을 기준으로인지 제시해 주세요

**Comment by kyahnu** [comment]
그리고 ./install_fonts.sh 로 코드스페이스에 한글 폰트를 설치는 제대로 한 상태인 건가요?

**Comment by jangjuntae** [comment]
버전을 정확히 어떤 것인지 모르겠어서 commit이 254개가 된 버전 상태입니다

**Comment by jangjuntae** [comment]
한글 폰트는 문제가 없는거 같은게 그냥 png가 생성이 되지 않습니다

**Comment by jangjuntae** [comment]
해결 완료 했습니다
