### ISSUE TITLE
test.py -d 옵션은 윈도우즈에서만 동작함

### ISSUE THREAD

**Issue by kyahnu** [oss2024hnu/coursegraph-py#260]
https://github.com/oss2024hnu/coursegraph-py/tree/9799e7077b46eb8e2324c653b78cdba025ce6a2e

이 버전을 기준으로

```
@kyahnu ➜ /workspaces/coursegraph-py (main) $ python ./test.py -d
sh: 1: del: not found
```

test.py -t 옵션으로 테스트로 파일을 생성하고 난 다음 
생성되었던 파일을 자동으로 지워주는 기능인 -d 옵션이 윈도우즈 이외의 OS에서는 동작하지 않음

결국은 이거 test.py는 없애고 빨리 Makefile로 대체되어야 할 거 같네요

**Comment by lunatic280** [comment]
#243 PR로  해결했습니다.
