### ISSUE TITLE
환경에 따라 pip가 아니라 pip3로 실행해야 하는 경우도 있음을 문서에 반영

### ISSUE THREAD

**Issue by svvchu** [oss2024hnu/coursegraph-py#264]
맥북 파이참에서 필요한 모듈을 설치할 때 pip install [모듈이름] 이 아닌 pip3 install [모듈이름] 으로 명령어를 입력해야 모듈이 설치되는 것으로 확인됐습니다. 그리고 __main__.py 실행하기 위한 옵션들에 대해 정확한 예시(어떻게 옵션을 넣어야 실행되는지 정확한 명령어) 도 README.md 파일에 추가해 주셨으면 좋겠습니다.

**Comment by kyahnu** [comment]
pip이냐 pip3이냐는 배포판이나 설치된 환경마다 다른 세부사항입니다. pip가 잘못된 것이 아닙니다.

옵션 활용에 대한 설명은 이미 README에 나와 있습니다.

그리고 지금은 `make test`를 실행하면 어떤 명령을 실행하면 테스트를 할 수 있는지도 나옵니다.

그래서 두번째 내용은 이슈거리가 아닙니다.

제목을 단순히 수정 이렇게 달지 말고 제목에도 정보가 드러나도록 작성 바랍니다.

**Comment by kyahnu** [comment]
제가 제목을 수정하겠습니다. 앞으로는 제목을 이렇게 정보 없이 추상적이고 표괄적으로 올리면 점수로 인정하지 않겠습니다.

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/blob/144ce6d2190d8a52a32557a84f359c26b5d8fe67/README.md#%EA%B0%9C%EB%B0%9C%ED%99%98%EA%B2%BD-%EC%84%A4%EC%B9%98-%EB%B0%8F-%EC%B5%9C%EC%B4%88%EB%A1%9C-%EC%8B%A4%ED%96%89%ED%95%B4-%EB%B3%B4%EB%8A%94-%EB%B2%95--%EC%9D%B4%EA%B2%83%EB%8F%84-onboarding-%EB%94%94%EB%A0%89%ED%86%A0%EB%A6%AC%EB%A1%9C-%EC%98%AE%EA%B8%B8-%EB%82%B4%EC%9A%A9%EC%97%90-%ED%8F%AC%ED%95%A8%EB%90%A9%EB%8B%88%EB%8B%A4

이 부분에 추가되어야 할 내용인 거 같은데

이 부분의 내용도 README.md 에서 onboading 디렉토리로 옮겨야 앞으로 합니다.

**Comment by kyagrd** [comment]
실수로 버튼을 잘못 눌러서 이슈를 닫았었는데 다시 열어 놨습니다.

**Comment by kyahnu** [comment]
일단 pip3 관련 내용이 README에 이미 반영되었기 때문에 이 이슈는 닫습니다.
