### ISSUE TITLE
fontutil.py에서 코드 중복을 막아야합니다.

### ISSUE THREAD

**Issue by Wonsoox** [oss2024hnu/coursegraph-py#265]
fontutil.py 파일을 보면 코드내용에서 중복되는 부분이 너무 많습니다.
딕셔너리로 중복되는 코드를 간결하게 만들어야합니다.

--------------------------------------------------------------------------------------
def get_system_font():
    flist = font_manager.findSystemFonts()
    data_list = []
    system = platform.system()

    if system == 'Windows':
        # Windows의 경우, 시스템 폰트 경로로 설정
        for v in flist:
            try:
                fprop = font_manager.FontProperties(fname=v)
                if fprop.get_name() == 'Malgun Gothic':
                    data_list.append({"name": fprop.get_name(), "file": fprop.get_file()})
            except:
                continue
        return data_list
    
    elif system == 'Darwin':
        for v in flist:
            try:
                fprop = font_manager.FontProperties(fname=v)
                if fprop.get_name() == 'Apple SD Gothic Neo':
                    data_list.append({"name": fprop.get_name(), "file": fprop.get_file()})
            except:
                continue
        return data_list
    
    else:
        for v in flist:
            try:
                fprop = font_manager.FontProperties(fname=v)
                if fprop.get_name() == 'NanumGothic':
                    data_list.append({"name": fprop.get_name(), "file": fprop.get_file()})
            except:
                continue
        return data_list
--------------------------------------------------------------------------------------

**Comment by kyagrd** [comment]
이거 이미 해결된 거죠? 아니면 알려주세요 다시 열어놓게

**Comment by Wonsoox** [comment]
넵 맞습니다!
