### ISSUE TITLE
각각의 소스코드 모듈에 대해서 좀 더 구체적인 문서화가 필요합니다.

### ISSUE THREAD

**Issue by jangjuntae** [oss2024hnu/coursegraph-py#272]
보통은 주석이라 부르는 python에서는 docstring이라 부르는 것을 사용해서 문서화를 하면 좋을 것 같습니다. pydoc 모듈을 사용하면 좋을 것 같습니다.
https://docs.python.org/ko/3.7/library/pydoc.html

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/297 여기서 일부 진척상황이 있었습니다.

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/311 여기서도 스키마체커 docstring 작업이 진행되었습니다

**Comment by kyahnu** [comment]
show_table 정도까지만 되면 이 이슈는 닫기로 하죠 아직 show_table 은 docstring 안달아놨으니

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/326 여기서 show_table 도 진행되었으니 일단 이 이슈는 닫죠
