### ISSUE TITLE
fontutil.py에서 예외처리를 추가했으면 좋겠습니다.

### ISSUE THREAD

**Issue by eongeung** [oss2024hnu/coursegraph-py#274]
어디서 시작하느냐에 따라 오류가 천차만별하게 생길 수 있습니다. 이 때문에, 어디서 오류가 났는지 예를 들어 fontuil.py에서 폰트를 찾지 못했다면 폰트를 찾지못했다는 오류 메세지를 줘 font에서 문제가 생겼다는 점을 알려줘야 합니다. 
fontutil.py 뿐만 아니라 많은 코드에 예외로 빠져나가는 코드가 없는 곳이 많기 때문에, 모두 예외 처리를 해야 한다는 코드를 작성해야 합니다.

**Comment by kyagrd** [comment]
예외처리를 모든 곳에서 해야 하는 것은 아닙니다. 코드에 따라서 다르고요.
그리거 에러처리는 무조건 예외처리로만 하는 건 아니고 리턴값으로 하거나 등등 다양한 시나리오가 있을 수 있습니다.
구체적으로 어떤 함수에서 해야 한다는 게 아니고 그냥 어떤 모듈에 예외처리를 하자라는 거는 너무 일반적인 내용이라 이슈로 부적합하다고 생각하여 반려합니다.
