### ISSUE TITLE
그래프 모양 조정

### ISSUE THREAD

**Issue by silversub1106** [oss2024hnu/coursegraph-py#276]
현재 그래프는 학기별로만 구분을 하기에
선이 복잡하고 가독성이 매우 떨어집니다.
학년별 배경색 및 학기 구분 점선이 추가된 만큼
그에 맞게 학년은 세로로 구분하고 학기는 가로로 구분하여 
그래프 모양을 보기좋게 조정하면 좋을 것 같습니다.

**Comment by kyagrd** [comment]
이거 가로가 학년 세로를 학기로 하기로 논의했었는데요

**Comment by kyagrd** [comment]
지금 다른 수정사항도 거기에 맞춰서 작성이 되고 있습니다

**Comment by kyagrd** [comment]
기존에 올라왔던 이슈를 확인하고 이슈를 제기해 주세요.
https://github.com/oss2024hnu/coursegraph-py/issues/220 여기에서 논의된 내용이니 관련 내용은 여기서 논의를 계속해 주시고요. 이 이슈는 반려하고 닫겠습니다. 따라서 관련 PR도 일단 반려합니다.

가로 학년 세로 학기 배치 말고 다른 배치 기능을 추가하는 것은 좋은데 

기존 배치를 바꾸지 말고 별도 세부 기능으로 추가해 주세요.

https://github.com/oss2024hnu/coursegraph-py/issues/220 에서 논의된 것처럼요.

**Comment by kyahnu** [comment]
학년은 세로로 구분되는 게 아니라 가로로 구분되는 거 아닌가요?
힌 학년이 세로 기둥 형식으로 가로로 옆으로 갈수록 다른 학년이 되니까 ...
음 말로 그림의 뱡항을 표현하려다 보니 지금 오해가 생긴 거 같은데 프로그램 실행해 보니까

학년은 그대로 가로고요, 학기가 지금 세로로 구분되는 것도 그대로고

표현이 전달이 안되서 반려한 거니까 다시 열고 PR도 머지 예정입니다.

한 학기 안에 과목들을 가로 배치에서 세로 배치로 바꾼거네요.

**Comment by silversub1106** [comment]
감사합니다. 어휘력이 부족하여 잘 전달되지 않았는데 다음에 이슈를 올리거나 PR할떄는 최대한 풀어서 작성하겠습니다.
