### ISSUE TITLE
gui를 실행시킬 때 경로설정이 필요합니다.

### ISSUE THREAD

**Issue by IVEGAEUL** [oss2024hnu/coursegraph-py#277]
gui에서 이미지를 불러오기 위한 경로설정을 필요해보입니다.

**Comment by kyagrd** [comment]
제목에 이슈 내용이 좀 더 잘 드러나게 그리고 내용을 좀 더 자세히 수정해 주세요.
이게 무슨 내용인지 저도 잘 이해가 안갑니다.

**Comment by kyagrd** [comment]
이해가 되는 이슈로 수정하거나 새로 내용이 전달되는 이슈를 올리면 반영하겠습니다.
일단 이 이슈는 반려하고 닫습니다
