### ISSUE TITLE
각 개발 환경 별 gui 디자이너 실행 법을 명시해야할 것 같습니다.

### ISSUE THREAD

**Issue by JWhyeok** [oss2024hnu/coursegraph-py#280]
현재 윈도우의 경우 디자이너 프로그램을 실행 할 수 있는 방법을 설치방법과 함께 명시 해두었지만 리눅스와 맥 os 환경에서는 디자이너 실행을 명시해주지 못했습니다.

**Comment by JWhyeok** [comment]
다음은 Linux 에서 qt디자이너를 실행하기위해 설치해야하는 방법입니다.
 $ pip3 install pyqt5  
 $ sudo apt install python3-pyqt5  
 $ sudo apt install pyqt5-dev-tools
 $ sudo apt install qttools5-dev-tools

위에 작성한 목록을 다운 한 후 

   $ designer
로 실행하면 qt 디자이너가 실행되어 사용할 수 있습니다.

**Comment by JWhyeok** [comment]
맥 os의 경우 2023년 9월까지 Pyqt5 를 직접적으로 설치하는 방법이 없었습니다.
23년 9월 이후에 pyqt에서는 맥os 에서도 pip로 설치할 수 있도록 공지하고 있습니다

설치하는 방법은 터미널이나 vscode 내에서 아래의 명령을 실행하는 겁니다.

- pip install pyqt5

![캡처](https://github.com/oss2024hnu/coursegraph-py/assets/162516396/57446c63-88b0-459a-985a-70c85bea3113)

위의 사진처럼 맥 os의 경우에도  pyqt를 pip 를 이용해 다운할 수 있습니다.

이후 윈도우와 같이 파이썬이 설치되어있는 경로로 이동 한 후, \Lib\site-packages\qt5_applications\Qt\bin 에 들어가면 desiner 실행파일이 있습니다.

**Comment by kyagrd** [comment]
이거는 댓글 내용을 그대로 작성해서 온보딩에 md 파일로 문서화하면 되겠네요

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/291 온보딩은 아니고 README.md 에 추가하긴 했지만 어쨌든 이슈는 해결된 걸로 보이기에 닫습니다.
