### ISSUE TITLE
제작한 코드가 어떤기능을 하는지 docstring을 이용하여 명시해야합니다.

### ISSUE THREAD

**Issue by JWhyeok** [oss2024hnu/coursegraph-py#281]
프로젝트가 진행될수록 코드가 변경되는일이 많아지기때문에 각 함수가 어떤기능을 하는지 명시해주어야합니다.

![11](https://github.com/oss2024hnu/coursegraph-py/assets/162516396/37b006b7-10bd-47c0-a948-62e82373608f)

위 사진과 같이 함수가 어떤 기능을 하고있는지 알려 주어야합니다.

**Comment by kyagrd** [comment]
자동으로 docString 템플릿 작성해 주는 vscode의 autoDocstring 플러그인을 아마 많이 쓸 거 같으니
그 플러그인의 형식을 docstring 형식을 따르면 무난할 거 같습니다.

**Comment by kyagrd** [comment]
이거 그리고 제목으로는 조금 알아보기 힘든데 중복 이슈에
https://github.com/oss2024hnu/coursegraph-py/issues/272 이거랑

그래서 이건 반려하고 닫습니다.
