### ISSUE TITLE
코드스페이스에서 한글 설치하는 방법

### ISSUE THREAD

**Issue by stayineverywhere** [oss2024hnu/coursegraph-py#284]
코드스페이스에서 한글을 설치하는 방법을 온보딩에 작성하면 좋을 것 같습니다. 
현재 온보딩에서 graph 와 table을 실행하는 코드의 경우 한글이 설치가 되어있지 않으면 에러가 발생하도록 작성되어 있습니다. 또한 test를 하기위해서도 한글이 필요하기 때문에 코드를 돌리기 위해서는 한글을 설치하여야 하는데 설치하는 방법을 모르는 분들을 위해 온보딩에 간략하게라도 작성하면 좋을 것 같습니다.

**Comment by stayineverywhere** [comment]
어떤 명령어를 써야 하는지 (ex ./install_fonts.sh)  또는 코드스페이스에서 폰트를 다운로드 하면 코드스페이스를 재부팅(?) 해야 하는걸로 알고 있기에 하는 방법등을 적으면 좋을 것 같습니다.

**Comment by kyagrd** [comment]
오늘은 또 다시 해보니까 새로 코드스페이스 가상환견을 만들어도
`./install_fonts.sh`를 실행한 다음에 폰트를 설치하면 `bash`라고 명령어를 한번 더 입력하거나
아니면 코드스페이스에서 터미널을 닫았다 새로운 터미널을 열면 되더라고요.
문서화가 필요하긴 한 거 같습니다.

**Comment by kyahnu** [comment]
이거 이미 README에 추가해 놓아서 이슈는 닫습니다
