### ISSUE TITLE
draw_course_structure 함수 개선

### ISSUE THREAD

**Issue by m222zu** [oss2024hnu/coursegraph-py#287]
show_graph.py의 draw_course_structure 함수에서 node_size=2000, arrowstyle='->', arrowsize=10과 같은 하드코딩된 값들은 코드를 처음 보는 사람이 이해하기 어렵고, 유지 보수할 때 오류를 일으킬 가능성을 높입니다.
코드의 다른 부분에서 같은 값을 반복해서 사용할 경우, 그 값을 변경해야 할 때 모든 부분을 찾아서 수정해야하므로 오류가 발생하기 쉽고 작업도 번거로워집니다.
따라서 코드 상단에 상수로 선언하거나 설정 파일에서 불러오는 방식으로 관리하는 것이 유지보수에 용이해보입니다.

**Comment by kyagrd** [comment]
아직 설정파일까지는 할 단계는 아닌 거 같고 일단 코드 상단에 상수라던가
상수 여러개가 지저분해 보이면 딕셔너리나 데이터클래스로 한 덩어리로 묶어놔도 되고요
