### ISSUE TITLE
학년과 학기별 노드 색상 변경

### ISSUE THREAD

**Issue by JWhyeok** [oss2024hnu/coursegraph-py#29]
좀더 시각적으로 표현하기위해 노드의 색을 구분하는것이 좋을듯 합니다. 학년별 노드 색상을 구분하고, 선수과목이 있는 경우 선수과목과 유사한 색상으로 만들어 구분하기 쉽게 만들면 좋을것 같습니다. 

노드 색상은 색상코드표를 지원하는것 같습니다.

**Comment by kyahnu** [comment]
학년별 색상은 굳이 다르게 할 필요가 있을까요? 학년/학기는 이차원 배치를 통해 나타나는 위치를 통해서 알 수 있을 거니까요.

선수과목과 유사한 색상으로 만드는 거는 나쁘진 않은 아이디어 같긴 한데요, 문제는 여러 개의 선수과목이 있는 경우도 있을 수 있는데 그럴 때는 어떻게 처리할지 애매하지 않나요? 거기에 대해 자동으로 뭘 해줄 수 있는지 ...

**Comment by JWhyeok** [comment]
우선적으로 학년별 로 분류 후 더욱 디테일 하게 분류할 수 있도록 작업할 예정입니다!
아직 데이터가 완전히 만들어진 것이 아니어서 우선적으로 학년별로 분류 후 보여지는 방식에 따라 변경하려합니다.

현재는 왼쪽부터 오른쪽으로 학년이 올라가는것으로 만들어져있습니다. 이것을 위에서 아래로 내려오는 방식으로 변경하기위한 첫번째 작업이라고 봐주시면 감사하겠습니다.

**Comment by kyahnu** [comment]
@JWhyeok 가로로 학년이 증가하게 해주세요. 그런 형식을 일반적으로 훨씬더 많이 사용합니다. 과목 이수체계도 검색해 보면 ... 그래서 세로로 바꾸지는 말아주세요.

**Comment by JWhyeok** [comment]
네 알겠습니다. 트랙에 따라서 색상을 정하도록 고민해보겠습니다.

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/issues/34 로 이슈 합침
