### ISSUE TITLE
show_graph.py 노드 겹침현상 해소필요

### ISSUE THREAD

**Issue by silversub1106** [oss2024hnu/coursegraph-py#292]
#285의 해결방안과는 조금 다릅니다.

현재 ce.yaml의 그래프에서는 복잡한 작대기를 제외하고도 노드간의 겹침 문제가 몇개 보입니다.

그로 인해 작대기의 가시성이 더 떨어지는 문제가 발생하여 이 부분을 조금 수정하는것이 좋을것 같습니다.

show_graph.py에서 노드 위치를 정하는
adjust_coordinates() 함수부분을 조금만 손보면 될 것 같습니다.

**Comment by silversub1106** [comment]
더좋은 방법이 있다면 그쪽으로 가는것이 좋을 것이고 어느정도 이전 이슈와 겹치는 부분도 있기는 하겠지만 현재 대놓고 시각적으로 보이는 문제 정도는 해소하고 싶어서 이슈에 올려보았습니다.

**Comment by kyahnu** [comment]
근데 이 이슈는 https://github.com/oss2024hnu/coursegraph-py/issues/22 의 연장선이니 새로 하는 것은 중복 이슈에 해당하니 이건 반려하고 닫겠습니다

추가 논의가 필요하다면 https://github.com/oss2024hnu/coursegraph-py/issues/22 여기서 논의해 주세요

비슷한 이슈가 여러개로 중복 분산되는 것은 효율적이지 못하고 이런 중복 이슈에는 점수도 부여하지 않습니다.
