### ISSUE TITLE
docstring 를 위해 코드에 주석을 달고 그 표준을 정해두는 것이 좋을것 같습니다.

### ISSUE THREAD

**Issue by LemonVein** [oss2024hnu/coursegraph-py#298]
코드 가독성과 처음 함수를 보는 사람에게도 간단한 힌트를 줄 수 있게 docstring을 위한 주석을 달아서, pydoc 을 통해 쉽게 확인 할 수 있으면 좋을 것 같습니다 그리고 코드를 전체적으로 PEP8 표준에 맞춰 깔끔하게 하는 작업도 있으면 좋을 것 같습니다.

**Comment by kyagrd** [comment]
docstring도 일종의 주석으로 볼 수 있는데 주석을 달자는 말은 ... 그냥 코드에 주석을 달자 라는 너무 일반적인 이야기라 이슈로는 적절할 거 같지 않고요.

PEP8 표준에 맞추는 거는 이상적인 의견이기는 하나 현실적으로는 불가능할 거 같습니다. 아직 프로젝트에 코드를 한번도 PR하지 않은 사람들도 부지기수인데 새로 참여하는 사람들에게 PEP8에 맞춰서 하라고 이해시키기도 설득시키기도 강제하기도 어려운 측면이 있습니다.

**Comment by kyagrd** [comment]
그리고 이미 docstring 작업을 하자는 이슈는 올라와 있습니다.

**Comment by kyagrd** [comment]
그래서 이건 특별히 구체적으로 진행시키기가 어려운 이슈이므로 닫겠습니다. 중복된 부분도 있고요.
다음부터는 중복사항을 확인하고 좀더 구체적인 이슈를 올려주세요.

**Comment by kyagrd** [comment]
이슈를 분산시키기보다는 관련 기존 이슈에서 논의합시다
