### ISSUE TITLE
GUI 계획도 이미지가 보이지 않습니다.

### ISSUE THREAD

**Issue by 1ostar** [oss2024hnu/coursegraph-py#299]
![image](https://github.com/oss2024hnu/coursegraph-py/assets/127176821/8a92a9ec-1b7d-480c-b7fe-4aa587f36088)
이미지가 안보입니다.
이 이미지 올린 분 수정이 필요해 보입니다.

**Comment by SiRyung** [comment]
제가 깃허브 link 이미지 삽입법을 잘 몰라서 그런 것 같습니다.
우선 저 깨진 이미지를 클릭하면 이미지가 정상적으로 로드는 됩니다.

**Comment by kyahnu** [comment]
github markodown 작성법을 안내하는 문서의 이미지 관련 내용을 참고해서 수정 PR 넣으면 될 거 같네요
https://docs.github.com/ko/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#images

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/309

여기 PR보면 이미지 링크를 클릭해도 보이지 않는다고 합니다. 링크가 이미지 올린 사람 디스코드로 로그인해 있을 때만 혹시 보이거나 하는 건가요?
