### ISSUE TITLE
94db0e8 버전에서 그래프 출력 시 한글 출력 오류 문구 발생합니다.

### ISSUE THREAD

**Issue by gocks77777** [oss2024hnu/coursegraph-py#300]
https://github.com/oss2024hnu/coursegraph-py/issues/270#issue-2297711950

전에 한번 수정했던 것 같은데, 계속 업데이트 되는 과정에 위 링크와 (#270 ) 비슷한 오류가 발생한 것 같습니다.
python coursegraph -i data/input.yaml -o out.png
명령을 실행하니 

![image](https://github.com/oss2024hnu/coursegraph-py/assets/162093033/130a0f79-cd41-4479-9e23-a03088a558b7)

이런 오류 문구가 출력됩니다. 그래프는 한글로 정상적으로 나옵니다.

**Comment by kyahnu** [comment]
PR로 해결된듯
