### ISSUE TITLE
노드의 크기 및 모양으로 인해 과목이름이 5글자가 넘어가면 노드를 벗어나는 이슈

### ISSUE THREAD

**Issue by blackchadol** [oss2024hnu/coursegraph-py#305]
94db0e8f23c680e2b1ed4505f3f3f5583410fa94 버전을 기준으로
<img width="309" alt="캡처" src="https://github.com/oss2024hnu/coursegraph-py/assets/62284856/2e2724fd-deb8-4067-9231-ceebab61883d">

test.yaml을 기준으로 coursegraph를 실행시켜본 결과 과목이름이 5글자를 넘어가면 노드를 벗어나는 것을 확인했습니다. 

<img width="532" alt="캡처2" src="https://github.com/oss2024hnu/coursegraph-py/assets/62284856/be0c117d-2bdf-4150-a87f-eb1f1fa29470">

상기 이미지 처럼 가로가 길고 세로가 짧은 사각형 형태의 노드가 과목이름을 담기에 적합할 것이며 노드를 벗어날 시 줄바꿈을 하여 출력해주는 기능이 있어야된다고 생각합니다.

**Comment by kyahnu** [comment]
아직 열려있는 중복 이슈이므로 반려합니다.
https://github.com/oss2024hnu/coursegraph-py/issues/16
이전에 올라온 이슈를 확인해 주세요.
