### ISSUE TITLE
schema_checker.py 를 실행할때 실행할 명령문을 함수에 묶었으면 좋겠습니다

### ISSUE THREAD

**Issue by LemonVein** [oss2024hnu/coursegraph-py#310]
현재 schema_checker.py 는 단독 실행하면 
맨 아래에 있는 
file_path = input("파일명을 입력해주세요: ")
validate_yaml(file_path)
명령문들이 다이렉트로 실행되는데 이러한 실행문들을 함수로 묶어서 다른 곳에서도 호출해서 쓸 수 있게 하던가
아니면 if __name__: '__main' : 같은 조건문에 넣어두는 것이 좋을 것 같습니다.

**Comment by kyagrd** [comment]
이거는 제가 직접 해결했습니다. 다른 PR이 들어와서 이걸 해결 안하면 문제가 발생해서
