### ISSUE TITLE
__main__.py 를 테이블로 출력 시 전 학생이수구분도 색을 다르게 하여 가독성을 높이면 좋을 것 같습니다.

### ISSUE THREAD

**Issue by ppoppy** [oss2024hnu/coursegraph-py#312]
![이미지 2024  5  23  15 18](https://github.com/oss2024hnu/coursegraph-py/assets/127175733/5b28dc98-3f70-4d53-8593-42a933e4cb51)
6296f27 버전에서 __main__.py 를 ce.yaml 데이터 파일을 넣어 테이블로 출력한 결과에서 학생이수구분인 전선, 전기, 전필의 종류를 잘 알아볼 수 있게 위의 예시처럼 색을 지정하여 출력하면 좋을 것 같습니다

예를 들어 전공기초는 베이지색, 전공필수는 노란색, 전공 선택은 하늘색으로 해놓으면 글씨가 작아도 구분을 쉽게 할 수 있을 것 같습니다.

**Comment by kyahnu** [comment]
주제가 거의 비슷한 너무 유사한 이슈는 이렇게 별도로 만들지 말고 이미 올라온 매우 관련있는 이슈에서 토론해 주세요. 반려합니다.
