### ISSUE TITLE
ce.yaml 파일 graph 실행 시 전기, 전선에 따라 화살표의 모양이나 노드의 색상을 바꿨으면 좋겠습니다.

### ISSUE THREAD

**Issue by tkdgns08523** [oss2024hnu/coursegraph-py#319]
0fdcf7d 버전 cd.yaml 파일을 552c444 버전 show_graph.py 파일로 실행시키면
![스크린샷(29)](https://github.com/oss2024hnu/coursegraph-py/assets/162093089/f9507ae2-3399-48be-96ef-d0bad49eb3e9)
이러한 모양으로 graph.py가 만들어지는데, 전기는 저희가 필수적으로 들어야 하는 것인 반면 전선은 필수적이진 않습니다.
graph로 출력 시에 전선과 전기를 구분할 수 있도록 화살표의 모양이나 노드의 색상을 더 추가했으면 좋겠습니다. ex) 현재 "->"(실선)의 모양을 전기로, "-->"점선의 모양을 전선을 가리키도록 하는 것처럼 화살표의 모양을 바꿨으면 좋겠습니다. 화살표가 아니더라도 노드의 색상을 전기 과목과 전선 과목의 차이점을 두어 이수체계도를 볼 수 있게 했으면 좋겠습니다.

**Comment by kyahnu** [comment]
중복 이슈이므로 반려합니다. 유사 주제에 대해서는 관련 항목에서 논의해 주세요

**Comment by tkdgns08523** [comment]
혹시 어느 부분에서 중복이 되었는지 알 수 있겠습니까?
