### ISSUE TITLE
패키지 자동설치

### ISSUE THREAD

**Issue by KimDongYeun** [oss2024hnu/coursegraph-py#32]
앞으로 모듈이 늘어날수록 필요한 패키지들 또한 늘어날 것입니다.
사용자의 컴퓨터에 수작업으로 설치할 필요없이
파일을 실행하면 필요한 패키지를 자동으로 설치해주는 코드를 작성하면 편할 것 같습니다.

업데이트 될 때마다 requirements.txt 파일에 필요한 패키지를 추가하고 있는 것으로 보입니다.
requirements.txt 파일을 불러와서 자동 설치하게끔 작성하면 좋을 것 같습니다.

**Comment by kyahnu** [comment]
지금 ai-concept-demo 디렉토리는 그냥 아이디어 끄적끄적 해보는 거고 이번 목요일 오전에
본격적으로 최상위 디렉토리 구조를 잡아서 할건데 나중에 거기 최상위 실행파일에다가 이걸 꼭 적용하고 싶으면
그때 가서 새로운 최상위 파일에다가 적용해 주세요.

상대경로도 고려하고 오류발생시 예외처리에 대해서도 생각하면서요.

**Comment by KimDongYeun** [comment]
확인했습니다. 최상위 디렉터리구조가 잡힌 후에 다시 고려해보겠습니다.

**Comment by kyahnu** [comment]
이거는 아무리 생각해도 불필요한 기능 같습니다. 다른 활동을 생각해서 해주세요.
