### ISSUE TITLE
데이터 검증 스키마 통합하는 것이 좋다고 생각합니다.

### ISSUE THREAD

**Issue by chuunbyul** [oss2024hnu/coursegraph-py#321]
schema_checker.py에서 정의한 데이터 검증 스키마를 다른 파일에서도 일관되게 사용하도록 합니다.

**Comment by chuunbyul** [comment]
from schema_checker import schema

def read_subjects(filename: str) -> Optional[strictyaml.YAML]:
    try:
        with open(filename, 'r', encoding='UTF8') as file:
            yaml_data = file.read()
            data = strictyaml.load(yaml_data, schema)
            return data['과목']
    except FileNotFoundError:
        print("해당하는 파일이 없습니다.", file=sys.stderr)
        return None
    except strictyaml.YAMLValidationError as e:
        print(f"YAML 데이터가 잘못되어있습니다: {e}", file=sys.stderr)
        return None
        
해당 코드로 스키마를 통합할 수 있습니다.

**Comment by chuunbyul** [comment]
프로필에 한글로 이름 수정했습니다!

**Comment by kyagrd** [comment]
일단 통합하는 코드는 PR로 들어오긴 했으니 이 이슈는 닫음
