### ISSUE TITLE
그래프 겹침 문제 개선 : adjust_coordinate의 작동구조 개선

### ISSUE THREAD

**Issue by Wonsoox** [oss2024hnu/coursegraph-py#327]
그래프 출력시에 겹침 현상이 나타나는 이유 :  1,2학기 좌표가 서로 간섭하도록 지정되고, 출력된다.
이는 키 : 쌍 값지정에서 학기조차도 다른 그룹으로 지정되어서 일어나는 현상이다.
예를 들어
학년  학기
(1    ,    1)  : [0,0,0]
(1    ,    2)  : [0]
(2    ,    1)  : [0,0]
(2    ,    2)  : [0,0,0,0,0]
문제는 이렇게하면 
adjusted_pos[pos_key][i] = (i - (num_positions - 1) / 2) * spacing
이 코드에서 개발자의 의도에서 벗어나게 작동하게 된다.
왜냐하면 저 코드는 (학년,학기)를 개별의 그룹으로 보아서 새로운 좌표 조정 값을 지정해주기 때문.
예시)
(1,1) : [-0.2,-0, 0.2]
(1,2) : [-0.4,-0.2,-0, 0.2, 0.4]
이런식으로.

그래서 필연적으로 학기 간 좌표 간섭이 생길 수 밖에 없고 이는 곧 노드의 심한 겹침으로 이어지게 된다.
따라서 이 현상을 해결해야 한다.

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/328 로 해결된 듯?
