### ISSUE TITLE
gui.py에서 만들어진 파일을 정리할 필요가 있을 것 같습니다.

### ISSUE THREAD

**Issue by lunatic280** [oss2024hnu/coursegraph-py#329]
gui.py를 이용해 이미지를 만들면 coursegraph에 생성됩니다.
![asdfsafsfsfasfsafsafs](https://github.com/oss2024hnu/coursegraph-py/assets/82097844/68bcd810-fd64-4178-a6ac-f8c8556d59af)

 여러 개를 만들면 디렉터리가 정리가 되지 않기 때문에 어느 디렉터리에 저장해서 정리하는게 좋을것 같습니다.

**Comment by kyahnu** [comment]
더 좋은 방법은 gui를 꼭 coursegraph 디렉토리로 들어와서 실행시키는 게 아니라 아무 곳에서나 실행시킬 수 있도록 하는 거죠. 그리고 기본적으로 현재 작업 디렉토리에 저장되도록 하고요.

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/330 로 해결
