### ISSUE TITLE
__main__.py를 실행하여 나온 창의 크기를 조절 할 때 그 요소들의 크기도 같이 변경되어야 할 것 같습니다

### ISSUE THREAD

**Issue by ppoppy** [oss2024hnu/coursegraph-py#337]
b05b11a 버전에서 __main__.py 에 ce.yaml을 선택해서 그래프로 실행했을 때
창 크기를 줄이거나 늘릴 때 그 안에 요소들도 같이 크기가 변해야 될 것 같습니다
첫 번째 사진은 전체화면일 때고, 두 번째 사진은 창의 크기를 줄였을 때 (차이를 보이기 위해 과도하게 줄였습니다) 입니다
아무래도 데이터가 많다보니 창의 크기를 줄였을 때 서로 겹쳐지는 문제가 있습니다. 
![image](https://github.com/oss2024hnu/coursegraph-py/assets/127175733/3aa46b7f-f96c-4888-b27c-eedb96f27bdf)
![image](https://github.com/oss2024hnu/coursegraph-py/assets/127175733/49e319e7-eea2-47c1-a717-dce8ea544465)

**Comment by kyagrd** [comment]
main CLI에서 이미지를 띄워주는 것은 보조적인 기능이고 저장하기 전에 파일 이름을 안정했으면 그냥 보여주는 정도. 그냥 파이썬 라이브러리에서 제공하는 show 기능을 활용할 뿐이라 저 UI는 라이브러리를 건드리거나 하지 않는 이상 고치는 데 한계가 있는 걸로 압니다.

**Comment by kyagrd** [comment]
이미지를 생성해서 이미지 뷰어로 보는 게 해결책이고, 아니면 GUI 만드는 데 합세해서 거기서 원하는 동작을 하는 UI를 만드는 것이 현실적입니다. 그래서 그냥 닫겠습니다.
