### ISSUE TITLE
gui.py에서 사용자의 입력을 통해 yaml 파일을 생성하는 기능이 있으면 좋겠습니다. 

### ISSUE THREAD

**Issue by blackchadol** [oss2024hnu/coursegraph-py#340]
b05b11adf6fa64a2b9f1cf746e47a90debbf3671 버전 기준으로 프로그램의 기능을 이용하려면 yaml 파일을 삽입해야합니다.
대부분의 일반인에게 yaml 파일은 생소할 것이고 이로 인해 프로그램 접근성이 떨어질 수 있습니다. 

![image](https://github.com/oss2024hnu/coursegraph-py/assets/62284856/c653cbd4-2dca-4472-81cc-98c3ba98b0fa)

위는 간단하게 예시를 보이기 위해 PyQt5를 이용하여 만든 yaml 파일 제조 프로그램이며 이것보다 더욱 편리한 형식으로 yaml 제조 gui를 만든다면 더욱 더 사용자 친화적인 프로그램이 될 수 있다고 기대합니다.

**Comment by kyagrd** [comment]
이건 GUI로 제한된 방법으로 입력을 제한해야히 텍스트 입력받으려면 무엇이 올바른 문법이고 무엇이 틀린 문법인지 명확히 정의해줘야 하고 문법이 틀렸을 때 문법 오류 내야 되고 하나의 프로그래밍 언어를 만든다고 보면 됩니다. 그래서 사람들이 JSON이나 YAML이나 TOML이나 이런 조금은 처음 보면 어색해 보이지만 이미 만들어 놓아서 많은 사람들이 쓰고 있는 설정파일 문법을 쓰는겁니다.

**Comment by kyagrd** [comment]
이 프로그램의 사용자는 일반인을 대상으로 기획하지는 않았고 우리가 그러니까 컴공/AI/멀티 등의 학생들과 교수님들이 쓰려고 하는거라 전공자들이면 TOML, JSON, YAML 정도는 적당히 적응해서 쓰는 게 정상이죠.

**Comment by kyagrd** [comment]
그래서 일반인까지는 고려할 필요는 없을 거 같습니다.

**Comment by kyagrd** [comment]
그리고 일반인을 진짜 고려하고 싶다면 텍스트로 형식으로 어떤 문법을 가정해서 입력받는다는 방식은 YAML이 일반인에게 어색한 것과 마찬가지 이유에서 어차피 안되고요.

**Comment by kyagrd** [comment]
일반인을 고려하려면 텍스트 데이터를 이렇게 통으로 입력하게 하면 안되고 GUI로 입력을 제한해서 필드마다 입력받도록 해야 할겁니다.

**Comment by kyagrd** [comment]
일반인이 SQL을 어려워하면 SQL에 해당하는 새로운 쿼리 언어를 만들어주는 게 말이 안되는 것과 마찬가지 이유로 좀 곤란하죠.

일반이닝 SQL을 어려워하면 엑셀같은 GUI를 제공하는 게 정석적이고 일반적으로 가능하다고 알려진 접근방식으로 알고 있습니다.

**Comment by kyagrd** [comment]
그림을 잘못 이해해서 댓글들을 잘못 달았는데, 지금 GUI로 입력을 받느 ㄴ게 맞네요

**Comment by kyagrd** [comment]
과목과 선수과목 뿐 아니라 다른 필수 항목들도 같이 입력을 받고 선택 행목도 입력할 수 있도록 하면 편의성을 제공하는 GUI가 될 거 같습니다.

**Comment by kyagrd** [comment]
생성하고 나서 스미카 검사도 한번 하면서 생성하고요
