### ISSUE TITLE
show_table 출력 이미지가 확대시에 해상도가 깨져 보입니다

### ISSUE THREAD

**Issue by Wonsoox** [oss2024hnu/coursegraph-py#345]
![오픈소스 1](https://github.com/oss2024hnu/coursegraph-py/assets/162536366/293e9bc5-51ea-4875-bf27-f42b6e186e09)

표 출력 이미지가 확대조작시에 글자와 표의 해상도가 깨져보입니다. 이를 고쳐야합니다.

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/346 로 해결된듯
