### ISSUE TITLE
__main__.py 실행 시 선의 색상을 변경하는 것이 좋아 보입니다. 

### ISSUE THREAD

**Issue by ppoppy** [oss2024hnu/coursegraph-py#347]
<img width="1299" alt="스크린샷 2024-06-02 22 25 23" src="https://github.com/oss2024hnu/coursegraph-py/assets/127175733/a4415466-cc90-485a-afc9-1e2e7833b221">
d47499e 버전에서 __main__.py ce.yaml 파일을 넣어 실행한 화면입니다.
많은 선들로 인해 구별하기 어려움으로, 선들을 구분하기 쉽도록 색을 다르게 하는 것이 좋아보입니다.
또, 학년은 구분이 되지만 학기는 구분하기 어려우므로 학기로 색을 나누는 것도 좋아보입니다.
1학기 초록색
2학기 핑크색
3학기 파란색
4학기 갈색
이런식으로 최대한 서로 겹쳐도 잘 보이는 색으로 바꾸는 것이 좋아보입니다!

**Comment by kyagrd** [comment]
선의 모양이 아니라 색을 구분하는 것이 더 나은 해결책인 이유는 무엇인가요?
