### ISSUE TITLE
input.yaml외에 같은 입력 형식의 다른 파일 추가

### ISSUE THREAD

**Issue by JWhyeok** [oss2024hnu/coursegraph-py#35]
빠르게 업데이트가 이루어짐에 따라 데이터 파일의 내용 역시 우선적으로 확정 되어야 한다고 생각합니다.
아래는 한남대학교 컴퓨터공학과의 2023년 전공 로드맵과 과목들이 나와있는 링크입니다.
하단 링크에 나와있는 과목으로 데이터를 수정한 후 코드를 수정하는 것이 알맞은 순서라 생각하여 요청합니다.
https://ce.hannam.ac.kr/roadmap/

**Comment by kyahnu** [comment]
파일 하나만 가지고 할게 아니라 input.yaml 말고 추가 입력 파일을 만들어서 파일 이름을 변경해 가며 실행할 수 있는 기능을 넣는 게 맞겠죠.

컴공 말고 다른 학과도 활용할 수 있는 걸 만들려는 거니까요 입력 내용만 바꾸면

**Comment by kyahnu** [comment]
일단 data 라는 디렉토리를 별도로 만들어 거기에 더미로 input.yaml과 같은 내용으로 더미로 채워놓을테니 내용 입력은 거기다 해주세요

**Comment by JWhyeok** [comment]
네 알겠습니다

**Comment by JWhyeok** [comment]
네 알겠습니다. 각기 다른 여러 데이터 파일을 모두 나타낼 수 있도록 고민해보겠습니다.

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/blob/main/data/ce.yaml

컴공 데이터를 입력해 놓고 싶으면 여기에다 해주세요

**Comment by JWhyeok** [comment]
네 우선적으로 컴공학과 데이터를 입력해두겠습니다.

**Comment by JWhyeok** [comment]
입력 후 pull request 해뒀습니다!

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/36 로 해결

**Comment by kyahnu** [comment]
오류가 있던 부분에 대해 고치는 PR https://github.com/oss2024hnu/coursegraph-py/pull/44 들어옴

**Comment by kyahnu** [comment]
참고로 현재 새로운 ce.yaml에 대해서 입력 테스트해 보는 방법은

```python
if __name__ == "__main__":
    # filename = os.path.join(script_dir, './input.yaml')
    filename = os.path.join(script_dir, '../data/ce.yaml')
```

이렇게 원래 `'./input.html'` 대신에 위와 같이  filename을 바꿔서 concept-demo.py를 실행해 보면  됩니다.
