### ISSUE TITLE
노드좌표배치 개선

### ISSUE THREAD

**Issue by Wonsoox** [oss2024hnu/coursegraph-py#351]
현재 노드좌표배치 수식은 간편하긴 하나 노드 개별의 좌표를 제어하기에는 적절하지 못하다고 생각됩니다. 기존의 수식으로 #343을 완료하려고 할 시에, 기준점 0으로부터 양수와 음수값이 나오기 때문에 
```
      (1)어 : -1.2
+-------+-------+------+------+-------+
| 　(2)어　|　어　|　　　|　배　|　　　|
| (3)어,기준　|　　　|　긋　|　　　|　치　|
| 　(4)어　|학년줄|　　　|　배　|　　　|
| 　(5)어　|추가　|　　　|　배　|　　　|
+--------+-------+------+-------+------+
     (6)어 : 1.2
```
이러한 상황에서 노드의 정렬이 쉽지 않다는 문제점이 있습니다.

따라서 첫번째 노드가 내부 그래프안에서 기준점(0,0)으로 정렬되야  이 문제를 좀더 쉽게 해결할 수 있다고 생각합니다.
따라서 기존의 노드배치 수식 구조를 개선해야 합니다.

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/352  로 해결
