### ISSUE TITLE
python coursegraph -i data/input.yaml -o out.png을 실행하면 오류가 발생합니다.

### ISSUE THREAD

**Issue by gocks77777** [oss2024hnu/coursegraph-py#353]
@gocks77777 ➜ /workspaces/coursegraph-py (main) $ python coursegraph -i data/input.yaml -o out.png
The output image file path has been specified: out.png
The input YAML file path has been specified: data/input.yaml
YAML 데이터가 잘못되어있습니다: while parsing a mapping
  in "<unicode string>", line 5, column 1:
      "\uD559/\uAC15/\uC2E4":
    ^ (line: 5)
unexpected key not in schema '학/강/실'
  in "<unicode string>", line 8, column 1:
      - '1'
    ^ (line: 8)
An error occurred: 'NoneType' object is not iterable

aac42aa 버전에서 오류가 발생합니다.

**Comment by kyagrd** [comment]
중복 이슈입니다 반려합니다
