### ISSUE TITLE
yaml 파일을 한번에 테스트를 하는 코드가 필요합니다

### ISSUE THREAD

**Issue by HeoSeungBeen** [oss2024hnu/coursegraph-py#355]
aac42aa3518261898c3dd9b37c9919ae6b79173c

버전에 대해 현재 yaml 파일이 총 5개가 존재하는데 코드를 수정할 때 마다 yaml 파일 하나하나에 다 테스트하기에
번거로운 상황이 발생합니다. 

이를 해결하고자 yaml 코드를 전부 한번에 테스트하는 방법이 필요합니다.

**Comment by kyagrd** [comment]
make test ???
반려합니다
