### ISSUE TITLE
프로젝트에 verbose 옵션 추가 필요

### ISSUE THREAD

**Issue by jangjuntae** [oss2024hnu/coursegraph-py#359]
최근 CLI에 더 자세한 정보를 출력하는 기능이 추가되었지만, 이 기능은 최종 사용자에게는 필요하지 않고 프로젝트에 기여하는 개발자에게만 유용합니다. 개발자나 디버그를 위해 필요한 상세 정보를 출력하는 이 기능은 일반적으로 `--verbose` 혹은 `-v` 옵션으로 처리됩니다.

처음에는 초기 인증 기능에 생성된 코드에서 verbose 옵션이 제거되었지만, 이제 다시 필요성이 제기되어 이 기능을 부활시키고자 합니다.

### 필요성
- 개발자 및 디버그를 위해 필요한 상세 정보 출력
- 프로젝트 기여자들이 더 효율적으로 작업할 수 있도록 지원

### 제안 사항
- verbose 옵션 추가 (`--verbose` 혹은 `-v`)
- 옵션 추가에 대한 구체적인 사용 사례와 예제 코드 작성

### 기대 효과
- 프로젝트 기여자들의 디버그와 개발 작업이 수월해질 것
- 상세 정보 출력을 통해 문제 해결 속도가 빨라질 것

**Comment by kyagrd** [comment]
이런 식을 이해하지 않고 구체성 없이 작성하면 반려합니다
