### ISSUE TITLE
로그레벨 조정 기능 요청

### ISSUE THREAD

**Issue by peyoon** [oss2024hnu/coursegraph-py#360]
현재 프로젝트에서는 단일 로그 레벨만 지원하고 있어, 특정 상황에서 불필요한 로그가 많이 출력되고 있습니다. verbose 옵션을 통해 로그 레벨을 조정할 수 있는 기능을 추가하여, 개발자들이 필요한 로그만 선택적으로 볼 수 있도록 개선이 필요합니다.

**Comment by kyagrd** [comment]
이런 식으로 구체성 없이 작성하면 안된다고 공지했을텐데요 반려합니다.
