### ISSUE TITLE
함수 호출 스택 트레이스 출력

### ISSUE THREAD

**Issue by peyoon** [oss2024hnu/coursegraph-py#361]
프로젝트 내에서 함수 호출 과정에서 발생하는 문제를 추적하기 어렵습니다. verbose 옵션을 통해 함수 호출 스택 트레이스를 상세히 출력할 수 있도록 기능을 추가해 주십시오.

구체적으로:
- 함수 호출 시점의 스택 트레이스
- 각 함수 호출의 매개변수 값
- 호출된 함수의 반환 값

이 기능은 함수 호출 과정에서 발생하는 문제를 신속히 파악하고 해결하는 데 도움이 될 것입니다.

**Comment by kyagrd** [comment]
이슈에 스팸하지 마세요
