### ISSUE TITLE
파일 I/O 작업 상세 로그

### ISSUE THREAD

**Issue by peyoon** [oss2024hnu/coursegraph-py#362]
현재 파일 입출력 작업에 대한 로그가 부족하여 파일 처리 과정에서 발생하는 문제를 파악하기 어렵습니다. verbose 옵션을 통해 파일 I/O 작업의 상세 로그를 출력할 수 있도록 기능을 추가해 주십시오.

구체적으로:
- 파일 읽기 및 쓰기 작업 로그
- 파일 경로 및 파일 크기 정보
- 파일 처리 상태 (성공, 실패 등)

이 기능은 파일 관련 문제를 쉽게 디버깅하고 처리할 수 있도록 도와줄 것입니다.

**Comment by kyagrd** [comment]
이해하고 작성한 내용이 아닙니다. 반려
