### ISSUE TITLE
더 많은 출력 형식을 지원하는 것도 괜찮다고 생각합니다.

### ISSUE THREAD

**Issue by chuunbyul** [oss2024hnu/coursegraph-py#369]
현재 그래프와 테이블 형식으로 출력이 가능한데, PDF, Excel 등 다른 출력 형식도 지원 가능하게 추가하고 싶습니다.
Excel의 경우 다른 필요한 문서를 작업할 때 활용할 수 있다면 좋을 것 같습니다.

**Comment by chuunbyul** [comment]
Excel의 경우 다른 필요한 문서를 작업할 때 활용할 수 있다면 좋을 것 같습니다

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/376 로 해결이 어느 정도 되었는데 엑셀이나 csv같은 걸 혹시 하고 싶은 사람이 있을까봐 닫지 않고 남겨놓습니다.

**Comment by kyagrd** [comment]
지금 dot 도 지원하고 상당히 다양해졌으니 일단 웬만큼 이 이슈는 해소되었다고도 볼 수 있으므로 일단 닫습니다
