### ISSUE TITLE
폰트 사용의 불편함

### ISSUE THREAD

**Issue by stayineverywhere** [oss2024hnu/coursegraph-py#37]
지원하지 않은 폰트의 경우 그래프에서 표현이 안되거나 오류가 발생하기에 따로 다운로드를 해서 사용해야 한다는 불편함이 있습니다. 설치가 안되어 있으면 설치가 안되어 그래프에서 글자그대로 표현이 안되고 네모로 표현이 되는등의 불편함이 있습니다. 폰트를 설치하게 되더라도 글자가 깨지는 경우가 있고 어떤 글자는 잘 작성되어 있는데 글자 중간에 네모가 들어가는 등의 불편함이 있어 폰트를 설치하지 않아도 그래프에서 표현이 될 수 있게 보완되었으면 좋겠습니다..

**Comment by kyahnu** [comment]
폰트를 설치하지 않고 볼 수 있는 방법은 없습니다. 그리고 지금 기본설치 폰트를 이용하는 것으로 개선하는 PR이 이미 올라와 있습니다.
이미 올라온 이슈와 PR의 내용을 확인하고 이슈를 올려주세요. 이 이슈는 반려하고 닫겠습니다.
