### ISSUE TITLE
show_table.py의 생성자 호출 시 인자 누락

### ISSUE THREAD

**Issue by seonghun0825** [oss2024hnu/coursegraph-py#372]
1. 'ShowTable' 클래스의 생성자를 호출할 때 인자가 누락되어 있습니다. 마지막 줄의  data_processor = ShowTable(None, False, False) 에서 None, False, False값에 필요한 인자를 올바르게 전달하면 좋을 것 같습니다.

2. 테이블을 생성할 때 적절한 크기를 설정하지 못해 오류가 발생할 수 있습니다. 그러므로 생성자에서 너비와 높이를 설정할 때 기본값을 추가하여 None 값이 들어오지 않도록 기본 너비와 높이 설정에 추가하면 좋을 것 같습니다.

**Comment by kyagrd** [comment]
이거 이제 해결된 거죠? 이거때문에 make test에서 에러나고 있었던 거 같은데
