### ISSUE TITLE
로그 기능 추가

### ISSUE THREAD

**Issue by leeseungho55** [oss2024hnu/coursegraph-py#378]
실행 중 발생하는 주요 이벤트 및 오류를 기록하는 로그 기능.
GUI와 CLI 모두에서 로그를 확인할 수 있도록 구현.

//예시 코드

const fs = require('fs');
const { app, BrowserWindow } = require('electron');

function log(message) {
    const timestamp = new Date().toISOString();
    const logMessage = `${timestamp}: ${message}\n`;
    fs.appendFileSync('app.log', logMessage);
}

function showLogs() {
    const logs = fs.readFileSync('app.log', 'utf8');
    console.log(logs);
}

function createWindow() {
    const win = new BrowserWindow({
        width: 800,
        height: 600,
        webPreferences: {
            nodeIntegration: true
        }
    });

    win.loadFile('index.html');

    win.webContents.on('did-finish-load', () => {
        const logs = fs.readFileSync('app.log', 'utf8');
        win.webContents.send('logs', logs);
    });
}

if (require.main === module) {
    if (process.argv.includes('--gui')) {
        app.whenReady().then(createWindow);
    } else {
        if (process.argv.includes('--log')) {
            log(process.argv[process.argv.indexOf('--log') + 1]);
        }
        showLogs();
    }
}

module.exports = { log, showLogs };

**Comment by kyahnu** [comment]
뭐죠 갑자기 index.html은? 여기 자바스크립트 프로젝트 아닙니다. 반려합니다.
