### ISSUE TITLE
과목 실습 여부

### ISSUE THREAD

**Issue by stayineverywhere** [oss2024hnu/coursegraph-py#38]
과목의 이해도를 높이기 위해서 실습의 여부를 표시하면 좋겠습니다. 실습의 여부가 표시되어 있으면 과목을 선택하거나 이해하는데 좀더 도움이 될 수 있을 것 같기 때문입니다. input.yaml 형식의 경우에는 선수과목 다음에 실습 여부에 관해 수정하면 좋을 것 같습니다.

**Comment by kyahnu** [comment]
알맞은 yaml 형식을 제안하고 https://github.com/oss2024hnu/coursegraph-py/tree/main/data 여기에 실제 컴공 데이터 사례에도 반영하는 PR을 작성해서 이 이슈를 해결하면 될 듯 합니다.

**Comment by stayineverywhere** [comment]
수정 후 pull request 해 놓았습니다!!

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/39 로 해결
