### ISSUE TITLE
#364에서 언급된 -v옵션을 README에 추가

### ISSUE THREAD

**Issue by Wonsoox** [oss2024hnu/coursegraph-py#382]
최근 개발자를 위한 노드 좌표출력 기능을 -v옵션으로 이용할 수 있게 변경되었습니다. 하지만 현재 README.md 파일에는 -v 옵션에 대한 사항이 없습니다. -v옵션을 안내함과 동시에 사용법에 대해서도 추가해야 합니다.

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/399
