### ISSUE TITLE
그래프여백을 조정해야합니다

### ISSUE THREAD

**Issue by Wonsoox** [oss2024hnu/coursegraph-py#383]
그래프여백이 너무 큽니다. 쓸데없는 빈공간을 너무 많이 만들어냅니다. 그래프 여백을 조정하여 이를 완화시켜야합니다.
![test](https://github.com/oss2024hnu/coursegraph-py/assets/162536366/600b3beb-a769-412b-b246-4a6d3043eae1)

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/384
