### ISSUE TITLE
make test 실행오류 발생

### ISSUE THREAD

**Issue by HeoSeungBeen** [oss2024hnu/coursegraph-py#390]
아래코드는 가장 최신 버전인 df80b03f76cfb90c8dd709fb6fc0495cc23e41cf 에서 make test 명령어가
table 옵션에서 다음과 같이 오류를 발생하는 것을 확인했습니다.
```
python3 coursegraph -f table data/ai.yaml -o out/ai_T.png
WARNING:root:Verbose level 0
An error occurred: 'ShowTable' object has no attribute 'create_image'
make: *** [out/ai_T.png] Error 1
```
뒷버전으로 하나씩 확인해보면 2cb051475d0e71251ca80e30bda81d713bdff468 버전까지는 오류가 발생
6917dbf0d5e896034eb8103ad1f891515ea6132b 버전은 오류가 발생하지 않는 것으로 보아 show_table.py 수정 이슈를 머지하는 과정에서 
make test 가 제대로 동작하지 않는 것을 확인할 수 있습니다.

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/394 로 해결
