### ISSUE TITLE
show_graph.py의 가독성 확보를 위한 코드 수정

### ISSUE THREAD

**Issue by tkdgns08523** [oss2024hnu/coursegraph-py#396]
[6e4c8f9](https://github.com/oss2024hnu/coursegraph-py/commit/6e4c8f9837ddcdf429bfeeff9555e06adf16d1f3) 버전에서 주어진 범주와 색상에 대응하는 범례를 그래프에 추가하는 작업을 하는 부분을 수정하고자 합니다.
![스크린샷(36)](https://github.com/oss2024hnu/coursegraph-py/assets/162093089/3d786a41-b891-4d93-aeb9-23ec031c8a5f) 
기존의 ↑ 이러한 코드에서
![스크린샷(37)](https://github.com/oss2024hnu/coursegraph-py/assets/162093089/6bcc6b02-9ce3-41aa-a963-43a04be45882) 
↑ 이런 코드로 수정하면 어떨까 합니다.
기존의 코드는 간결해 보이지만, 코드에 익숙하지 않은 사람들에게는 이해하기 어려울 수 있다는 단점이 있습니다. 수정한 코드는 반복문을 통해 코드의 실행 과정을 더 명확히 확인할 수 있습니다. 또한 모든 작업이 한 줄에 있던 예전의 코드는 변수를 확인해 디버깅 하기가 어렵다는 단점이 있지만 수정한 코드는 각 단계에서 변수 값을 출력하거나 디버깅이 더 원활해 코드를 확장하거나 수정할 때 유리하다는 장점이 있을 거 같습니다.

**Comment by kyagrd** [comment]
텍스트로 작성해 주세요

**Comment by kyagrd** [comment]
우리 1,2학년 파이썬 프로그래밍에서 다 배운 내용인데요 리스트 조건제시법 list comprehension 그 수업의 내용을 모두 소화한 사람들은 그다지 어렵다고 생각하진 않을 거 같습니다.
