### ISSUE TITLE
CLI 입력에서 pygraphviz를 출력하기 위한 dot 형식의 옵션를추가하면 좋을거 같습니다.

### ISSUE THREAD

**Issue by Wonsoox** [oss2024hnu/coursegraph-py#398]
pygraphviz로 그래프를 만들때 필요한 dot형식을 출력하는 옵션을 추가하여 pygraphviz를 작동시킬 수 있었으면 좋겠습니다. 또한 기존의 -f graph옵션과 헷갈리지 않도록 명확히 구분되게 만들면 좋겠습니다.

**Comment by kyagrd** [comment]
fb089d297a9e340c52000694e99cad16fceac8a1 버전에서 추가되었습니다.
