### ISSUE TITLE
 그래프 노드간 겹침 문제

### ISSUE THREAD

**Issue by blackchadol** [oss2024hnu/coursegraph-py#4]
04981f668c59aa84e3b7c98558ef5c48642f85a8 버전을 기준으로 ai-concept-demo를 실행해보면  그래프의 노드가 겹쳐보인다는 문제가 있습니다. input.yaml 기준으로 겹치는 과목이 영어와 수학인데 이 두 과목은 유일하기 같은 학년,학기에 겹치는 과목들입니다.  concept-demo.py의 코드를 보면 학년을 x좌표 학기를 y좌표로 노드를 배정하여 그래프를 그리는데 이러한 방식은 같은 학년과 학기에 2개이상 과목이 있을때 해당 노드들이 서로 겹치게 됩니다.

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/5 로 해결된 것으로 보임 아직 테스트를 한번 해봐야 하므로 테스트한 후에 close 예정

**Comment by kyahnu** [comment]
일단 현재 input.yaml로는 해결된 것으로 보임
