### ISSUE TITLE
기본 출력 화면 사이즈 조정

### ISSUE THREAD

**Issue by JWhyeok** [oss2024hnu/coursegraph-py#40]
출력 화면에 입력되는 데이터가 늘어남에 따라 기본 출력 화면의 사이즈를 더 크게 넓혀야할것같습니다.

현재는 matplotlib의 기본 사이즈로 결과물이 출력 되어 보여집니다.

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/43 로 해결
