### ISSUE TITLE
make test로 그래프 생성시 ce외에 다른 학과 이수체계 그래프가 이상하게 배치됨

### ISSUE THREAD

**Issue by sominoh** [oss2024hnu/coursegraph-py#400]
![1](https://github.com/oss2024hnu/coursegraph-py/assets/145252436/e5a4cc32-2894-497c-8616-5ed6fc7c5327)
![2](https://github.com/oss2024hnu/coursegraph-py/assets/145252436/c70b21ae-a8d5-4ca1-b3fd-460ec7f03730)
![3](https://github.com/oss2024hnu/coursegraph-py/assets/145252436/137a621d-1ebb-4271-ab11-7b6468f727ed)
![4](https://github.com/oss2024hnu/coursegraph-py/assets/145252436/abefb420-a1b6-4dae-b801-3768cb75c9ad)

**Comment by sominoh** [comment]
코드스페이스로 이미지 파일 만들어 볼 때만 문제가 생기는 것으로 보아 코드스페이스 안에서 실행해보면서 해결해야할 것 같습니다.

**Comment by kyagrd** [comment]
코드스페이스 뿐만 아니라 직접 컴퓨터에 설치한 파이썬 개발환경에서도 마찬가지로 에러납니다.

ce.yaml만 모양이 제대로 나오는지 확인하면서 코드를 변경하고 있어서 일반적인 경우에 레이아웃이 깨지는 뭔가 이상한 방식의 배치를 하고 있는 거 같습니다.

아니면 ce.yaml 파일 말고 다른 원본 파일에 오류가 있다거나 하는 걸텐데 그러진 않을 거 같고 ...

**Comment by kyagrd** [comment]
input.yaml 을 그린 그래프는 또 나름 멀쩡하게 나오는 거 같네요
