### ISSUE TITLE
.yaml 배치 문제

### ISSUE THREAD

**Issue by tkdgns08523** [oss2024hnu/coursegraph-py#404]
[e2852c5](https://github.com/oss2024hnu/coursegraph-py/commit/e2852c5c83e6adf0b09aaf28075ad27f72d2a0c5) 버전 show_graph.py파일로 모든 .yaml 파일들을 vscode로 실행해 봤을 때 #400 이슈와 같이 노드의 배치가 이상하게 나타남을 발견했습니다. ce.yaml 파일을 예로 들자면
![스크린샷(32)](https://github.com/oss2024hnu/coursegraph-py/assets/162093089/6b75de5b-6c15-4502-943d-677f41a49850)
원래는 이런 식의 배치를 시각화 했으나 현재는 
![스크린샷(38)](https://github.com/oss2024hnu/coursegraph-py/assets/162093089/a5f1dea2-af0c-4a75-a64c-35123c5e170f)
이런 식의 배치가 나오고 있습니다.
학기의 노드가 짤리는 것으로 봐선 그래프의 여백의 크기를 다시 조정하고, 정확히는 잘 모르겠으나 모든 .yaml 파일을 실행했을 때 y축의 좌표 값이 유동적으로 변해 배치가 이상하게 되는 것 같습니다. 코드에서 y축의 좌표 값을 수정해야 할 것으로 보입니다.

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/420/ 으로 해결
