### ISSUE TITLE
그래프 학기 구분선 오류

### ISSUE THREAD

**Issue by Wonsoox** [oss2024hnu/coursegraph-py#413]
![캡처](https://github.com/oss2024hnu/coursegraph-py/assets/162536366/3a266b59-749d-4f6b-906a-eee2ad7abbd1)

학기 구분선이 다시 복원되는 작업을 진행한것으로 알고있습니다. 하지만 오류가 존재합니다. 
```
min_y = min(y for _, y in pos.values())
    max_y = max(y for _, y in pos.values())
    center_y = (min_y + max_y) / 1.75
    plt.axhline(center_y, color='black', linestyle='-', linewidth=2)
```
코드에서는 최고/최저 값을 통하여  딱 중앙에 놓을려는 시도가 보입니다. 저 수식은 화면의 크기에 따라서 위치가 조금씩 달라지기에 1.75라는 숫자도 화면을 보고 작업자가 수동으로 조정한듯 합니다. 그러나 이 코드는 오히려 역효과를 불러옵니다. 왜냐하면 plt기반의 함수들은 대부분 사전에 정해둔 비율안에서 움직이고(희미하게 보이는 y그리드값이 0,1,2를 나타냄)  또한 현재 그래프 작업 파일에서 pos변수가 가지고있는 값은 노드들의 좌표 값인데 이를 기반으로 2로 나누거나 사용자 임의값으로 나누게 된다면 노드의 값이 불규칙함에 더불어서 더욱 본래의 의미를 잃고 오작동하게 되는 결과를 가져옵니다. 따라서 저 코드를 plt기반으로 제대로 작동하도록 수정하거나, 본래의 의미대로 학기를 인식하여 학기를 나누게 하는 기능을 가지게하거나, 기존 배경에서 절대적인 기준을 제공하여 노드들이 기준으로 학기를 나누게 작동할수있도록 정확히 둘로 나누게 수정해야합니다.

**Comment by kyagrd** [comment]
최근 관련 PR이 들어와서 머지를 하긴 했는데 충돌이 나서 제가 그냥 PR 작성자 버전 걸로 해서 충돌 해결해서 머지했거든요.
지금 제대로 수정이 된건가요? 이슈가 해결이 되었는지 현재 이 저장소 main 브랜치에서 ,,, ???

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/420 이 PR로 해결된 거 맞죠?

**Comment by Wonsoox** [comment]
넵 해결되었습니다.

**Comment by kyagrd** [comment]
일단 닫겠습니다.
