### ISSUE TITLE
노드 수정

### ISSUE THREAD

**Issue by leesang01** [oss2024hnu/coursegraph-py#416]
c54222c 버전에서의 ce.yaml 실행 화면입니다.
현재 1학기만 노드로 보여지고 있습니다.
2학기 노드도 보이도록 코드를 수정하면 좋을 것 같습니다.
<img width="1048" alt="123" src="https://github.com/oss2024hnu/coursegraph-py/assets/162536355/9a992287-0841-4efa-87f4-dc479749299d">

**Comment by kyagrd** [comment]
최근 이와 관련된 PR이 올라와서 머지했는데 이제 이 이슈는 해결이 된건가요?

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/420 PR 작성한 분이 결과 캡춰까지 해서 설명한ㄴ 바에 의하면 해결된 듯 합니다.
