### ISSUE TITLE
dot 오류나는 이유

### ISSUE THREAD

**Issue by eongeung** [oss2024hnu/coursegraph-py#417]
#411 #412
다른 부분에서 dot 이 오류나고 있다는 이슈가 있는데 찾아보니 dot 유틸리티가 graphviz 패키지의 일부라 아마 설치하지 않고 실행하여 그런 것 같습니다. 패키지 자동 설치 때 graphviz도 있으면 좋겠습니다.

**Comment by kyagrd** [comment]
오류가 나도 그래서 make test가 멈추지 않고 그냥 넘어가도록 했습니다.

**Comment by kyagrd** [comment]
그래서 오류가 나더라도 dot 파일까지는 생성이 되고 다른 graph나 table 테스트까지 진행이 됩니다.

**Comment by kyagrd** [comment]
이 이슈는 그래서 문제가 되지 않으므로 그냥 닫습니다.
