### ISSUE TITLE
코드 변경 시 주의 점 표시

### ISSUE THREAD

**Issue by tkdgns08523** [oss2024hnu/coursegraph-py#421]
graph 파일이나 table 파일을 변경 시 바르지 않은 값을 넣어 오류가 나는 부분이 있습니다. 코드를 변경할 때 실행을 안했거나 부분적으로 실행을 한 후 PR을 해서 문제가 발생했을 것이라 생각됩니다. 그래서 코드 내에 주석으로라도 변경하면 안되는 코드 값이나 이런 것들을 쓰면 어떨까 합니다.

**Comment by kyagrd** [comment]
이걸 미리 예상을 할 수가 없습니다.
바꾸지 않야야 할 곳을 미리 예상할 수 있는 구체적인 아이디어가 있으면 다시 이슈로 올려주세요.

미션 임파서블에 가까운 듯 하여 일단 이건 반려합니다.
