### ISSUE TITLE
데이터의 필수 요소에 대해 유효성 검사가 더 필요할 것 같습니다.

### ISSUE THREAD

**Issue by jjapagetti** [oss2024hnu/coursegraph-py#429]
show_table.py에서 데이터 입력 시 '과목' 키가 데이터에 존재하지 않거나, 빈 데이터일 경우에 데이터의 필수 요소에 대해 더 강력한 유효성 검사가 필요할 것 같습니다.

**Comment by kyagrd** [comment]
과목이 아니라 과목명 아닌가요? 과목명은 지금 필수로 검사하지 않나요?

**Comment by kyagrd** [comment]
이거는 이후로 추가 피드백이 없어서 반려하겠습니다.
