### ISSUE TITLE
dot 파일생성시에 파일글자깨짐오류

### ISSUE THREAD

**Issue by Wonsoox** [oss2024hnu/coursegraph-py#430]
dot포맷으로 프로그램 실행시 dot파일이 생성되는데ㅣ
/* Generated by GvGen v.1.0 (https://www.github.com/stricaud/gvgen) */

digraph G {
rankdir=TB;ranksep=1.25;
   subgraph cluster1 {
   label="1-1";
      node38 [shape="note",label="���������"];
      node39 [shape="note",label="���̽����α׷���I"];
      node40 [color="green",style="dashed",label=""];
   }
   subgraph cluster8 {
   label="4-2";
      node9 [shape="note",label="����AI�ǽ�II"];
      node10 [shape="note",label="������"];
      node11 [shape="note",label="�������ΰ�����"];
      node12 [shape="note",label="�ΰ������ǹ�������"];
      node47 [color="green",style="dashed",label=""];
   }
   subgraph cluster7 {
   label="4-1";
      node13 [shape="note",label="AI�����ν�����"];
      node14 [shape="note",label="����AI�ǽ�I"];
      node15 [shape="note",label="�ΰ����ɿ��������"];
      node16 [shape="note",label="ĸ���������"];
      node46 [color="green",style="dashed",label=""];
   }
   subgraph cluster6 {
   label="3-2";
      node17 [shape="note",label="�ڿ���ó��"];
      node18 [shape="note",label="��������"];
      node19 [shape="note",label="�ð迭�����ͺм�"];
      node20 [shape="note",label="��ȭ�н�"];
      node21 [shape="note",label="�������ͽ����񽺵����Υ�"];
이런식으로 한글부분이 깨져서 나옵니다.
show_graph파일에서 read_subjects함수에서 인코딩을 제대로 읽는 절차가 있음에도 글자가 깨지는 현상이 일어납니다.

**Comment by kyagrd** [comment]
이게 리눅스에서 locale이 한국어 유니코드일 때는 발생하지 않는 이슈인데 윈도우즈에서는 발생하나보군요
