### ISSUE TITLE
dot파일은 그래프를 출력하고 필요가 없으면 제거하였으면 좋겠습니다.

### ISSUE THREAD

**Issue by Wonsoox** [oss2024hnu/coursegraph-py#432]
dot파일이 사용자가 궁극적으로 원하는 매체도 아닐뿐더러, 그래프 이미지로 dot파일을 치환하다보면, 치환하고 남은 dot파일들이 쓰레기처럼 쌓일거 같습니다. 혹은 dot파일들을 모아놓거나, 일정기간이 되면 삭제하는 방향으로 가도 좋을거같습니다. 또는 cli환경에서 옵션을 주어서 dot파일을 저장하는 옵션도 넣는 방향으로 가서 필요하면 저장하여 보관하고 필요없으면 자동 삭제로 하여 관리하면 좋을거 같습니다.

**Comment by kyagrd** [comment]
dot 파일은 일부러 남겨놓으려고 하는 거라서요. 원한다면 그걸 수동으로 핸드튜닝해 볼 수도 있기 때문에요.

**Comment by kyagrd** [comment]
graphviz가 설치되지 않은 환경에서도 (이거 윈도우즈에 설치하면 좀 귀찮은 걸로 알고 있어서) 유틸리티가 정상 작동하고 dot 소스파일이 떨어져서 dot를 그림으로 변환해주는 웹사이트에서 활용한거나 할 수 있게 하려고 한 겁니다. 처음 프로젝트 참여하는 사람은 graphviz를 아마도 안 깔 거 같아서요.

**Comment by kyagrd** [comment]
현재 파이썬 CLI는 파이썬 graphviz api를 지금 사용하고 있는 게 아니라 dot 소스파일을 생성해주는 라이브러리를 사용하고 있습니다. graphviz에 의존성 없이요

**Comment by kyagrd** [comment]
그래서 이 이슈는 그냥 닫겠습니다.
