### ISSUE TITLE
.yaml 파일들의 내용 수정

### ISSUE THREAD

**Issue by HeoSeungBeen** [oss2024hnu/coursegraph-py#436]
c54222c41119295820eba9194eb73ee2677e0ce6 버전을 기준으로
yamlSchema.txt 에 따르면 
http://convac.animakid.gethompy.com/?page_id=11563 
해당사이트를 yaml 파일의 공식 명칭으로 설정하기로 했으나

현재 yaml 파일들은 해당 사이트의 내용과 맞지 않는 부분이 존재합니다.
ai.yaml 파일의 내부를 예시로 들면
```
과목:
  - 학년: 1
    학기: 1
    과목명: 선형대수학
    실습여부: yes
    구분: 전기
  - 학년: 1
    학기: 1
    과목명: 파이썬프로그래밍I
    실습여부: yes
    구분: 전기
```
이런 형식으로 표현되어있는데 
<img width="374" alt="스크린샷 2024-06-15 오후 1 56 49" src="https://github.com/oss2024hnu/coursegraph-py/assets/142968253/33a5290c-395a-40d6-9ad2-55778d307eab">
실제로 공식 홈페이지에 따르면 선형대수학은 실습이 존재하지 않는 수업입니다.
학과 공식 홈페이지에 맞게 yaml 파일의 내용이 수정되는게 급한건 아니지만 이슈로 올립니다

Ai 융합학과 https://ai.hannam.ac.kr/%ea%b5%90%ea%b3%bc%ea%b3%bc%ec%a0%95%ed%8e%b8%ec%84%b1%ed%91%9c/
멀티미디어 공학과 http://multi.hannam.ac.kr/sub3/menu_2.html

**Comment by kyagrd** [comment]
> yamlSchema.txt 에 따르면
> http://convac.animakid.gethompy.com/?page_id=11563
> 해당사이트를 yaml 파일의 공식 명칭으로 설정하기로 했으나

 여기 웹사이트에는 MD 정보만 나오지 실습여부는 안나오지 않나요?

**Comment by kyagrd** [comment]
어쨌든 맞지 않는 정보가 있으면 수정하는 건 의미가 있긴 할텐데요

**Comment by HeoSeungBeen** [comment]
공식 학과 홈페이지 추가해서 수정하겠습니다

**Comment by kyagrd** [comment]
이거 해결된 이슈인가요?

**Comment by HeoSeungBeen** [comment]
아직 해결 안된걸로 알고 있습니다 제가 곧 PR 해서 올리도록 하겠습니다.
