### ISSUE TITLE
과목 속성에 따른 노드 색상 표현 show_dot.py

### ISSUE THREAD

**Issue by HeoSeungBeen** [oss2024hnu/coursegraph-py#457]
과목 구분을 좀 더 직관적으로 하기 위해
과목 속성(전선, 전기) 에 따라 노드 색상을 다르게 했으면 좋을 듯 합니다.

127a5e3674d15905cadc0a5ca9080f4a4713636f 버전기준으로 모든 노드가 흑색이다 보니
가시성 확보와 과목 특성을 한눈에 파악하기 어렵습니다

**Comment by kyagrd** [comment]
이거 최근 PR들에서 해결이 어느 정도는 된 거 같아 닫습니ㅏㄷ
