### ISSUE TITLE
plotly를 사용하면 시각화가 더 잘 표현될 것 같습니다

### ISSUE THREAD

**Issue by jangjuntae** [oss2024hnu/coursegraph-py#47]
https://plotly.com/python/

**Comment by kyahnu** [comment]
graphviz 쪽이 우리가 원하는 클러스터링이나 이런 기능을 지원하는 거 같습니다

**Comment by kyahnu** [comment]
이거는 그냥 추측이니까 실제 우리 과목이수쳬계도와 관련있는 사례 이미지 캡춰를 가져와서 설득이 되면 부활시키고 일단은 닫도록 하겠습니다.
