### ISSUE TITLE
프로그램에 대한 문서화 작업이 필요합니다

### ISSUE THREAD

**Issue by Roviil** [oss2024hnu/coursegraph-py#48]
어떤 프로그램인지, 어떻게 실행하는지, 오픈소스 개발에 참여하는 방법 등에 대한 README.md 파일 수정이 필요해보입니다.

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/80 로 일정 부분 해결

문서화는 끝없는 작업이므로 어정도로 시작했다는 걸로 이슈를 일단은 닫겠습니다.
