### ISSUE TITLE
show_dot.py의 output_file 파라미터 예외 처리

### ISSUE THREAD

**Issue by m222zu** [oss2024hnu/coursegraph-py#486]
show_dot.py에서 output_file 파라미터가 제공되었을 때 파일쓰기 권한이 없거나 디스크 공간이 부족한 경우를 대비하여 try_except 블록을 사용해 예외를 처리하도록 하는 것이 좋을 것 같습니다.

**Comment by kyagrd** [comment]
최근 들어온 PR은 머지하고 살펴보니 오류가 있어서 다시 수동으로 원복하고 점수는 다시 감점하고 이슈는 다시 열어놓습니다.
