### ISSUE TITLE
Python만으로는 화살표의 표시가 어려울 것 같습니다.

### ISSUE THREAD

**Issue by JWhyeok** [oss2024hnu/coursegraph-py#49]
Java script 또는 c# 에서 제공하는 그래픽 라이브리를 사용하면 좋을것같습니다.

**Comment by kyahnu** [comment]
이거는 이 repository 내용이라고 하긴 조금 애매해서 ... 일단 닫겠습니다.
좀더 알아보고 추후에 JS나 C#으로 새로운 repository로 시작해서 개척하고 싶은 결심이 서면 알려주세요
