### ISSUE TITLE
읽어들일 파일을 사용자가 입력할 수 있게 바꿔야 할것 같습니다

### ISSUE THREAD

**Issue by jangjuntae** [oss2024hnu/coursegraph-py#50]
파일이 고정이 되어 있으면 사람들이 원하는 파일을 시각화 하기에 어려움이 있을 것 같습니다

**Comment by kyahnu** [comment]
이건 이제 `__main__.py`에 --input 같은 옵션을 활용해서 할 계획이니까 CLI 인터페이스에 대한 계획은 대략적으로 서 있고 실제로 코드 내용만 작성하면 해결될 것 같습니다.

**Comment by kyagrd** [comment]
이것도 완료됨
