### ISSUE TITLE
show_dot.py 파일 내 print_dot 함수 종합 개선

### ISSUE THREAD

**Issue by peyoon** [oss2024hnu/coursegraph-py#511]
현재 print_dot 함수에서 파일 저장 시 발생할 수 있는 IOError와 일반적인 Exception을 catch하고 있습니다.
하지만 이외에도 발생할 수 있는 예외들(예: TypeError, ValueError 등)에 대한 처리가 있으면 함수의 안정적인 구현이 필요할 수 있습니다.
이러한 예외들을 포괄적으로 처리하여 함수의 안정성을 높일 수 있습니다.
각 예외에 대해 적절한 처리 방식(예: 에러 메시지 출력, 대체 동작 수행 등)을 구현하면 좋을 거 같습니다.

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/532
