### ISSUE TITLE
show_dot.py에서 비효율적인 루프의 개선이 필요해 보입니다.

### ISSUE THREAD

**Issue by awc0596** [oss2024hnu/coursegraph-py#514]
현재 노드가 없는 경우를 처리하는 로직이 주석 처리되어 있었고, 이 부분이 필요한 상황을 고려하지 않은 채로 주석 처리되었습니다. 
이를 개선해서 간결한 코드를 만들면 좋을 것 같습니다.

**Comment by kyagrd** [comment]
내용이 이해가 안가는데 현재 실행되는 (주석처리되지 않은) 코드 중에 비효율적인 부분이 있어서 개선을 해야 된다는 거에요

아니면 효율과는 관계없이 주석처리된 부분이 많아서 정리를 해야 한다는 거네요?

제목이랑 내용이랑 따로따로라 이 파일을 처음 작성한 저도 이해가 안가는데, 이게 다른 사람들에게도 잘 이해가 안될 거 같습니다.

일단 반려하고 다시 제목과 내용이 일치해서 잘 전달되는 이슈를 작성해 주세요
