### ISSUE TITLE
show_dot.py에서 비효율적인 루프의 개선이 필요해보입니다.

### ISSUE THREAD

**Issue by awc0596** [oss2024hnu/coursegraph-py#519]
이전 코드에서는 노드가 없는 경우를 처리하는 로직이 주석 처리되어 있습니다.
'subGdict' 및 'nodedict' 를 딕셔너리 컴프리헨션을 사용해 초기화하고, 모든 학기별 노드를 먼저 생성한 뒤, 노드 연결 처리를 개선이 필요해 보입니다.
각 과목과 관련된 스타일 적용 또한 한 곳에서 처리되어, 노드 생성 로직과의 중복을 제거했습니다.

**Comment by kyagrd** [comment]
이미 PR이 올라온 해결책까지 나와버렸으니까 이슈거리가 더 이상 될 수 없습니다. 반려합니다.
