### ISSUE TITLE
프로그램 실행시 결과적으로 출력되어진 이미지를 저장 할 수 있도록 만들어야할것 같습니다.

### ISSUE THREAD

**Issue by JWhyeok** [oss2024hnu/coursegraph-py#52]
아직 활발하게 업데이트가 이루어지고있는 상황에서는 필요 없을 수도 있지만 결과적으로 만들어진 이미지를 저장하는 기능을 만들어 주석처리 해두면 좋을 것 같습니다.

**Comment by kyagrd** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/156 표 기능은 이걸로 추가가 되었는데요

**Comment by kyagrd** [comment]
이것도 완료됨
