### ISSUE TITLE
전공 기초 과목 분류

### ISSUE THREAD

**Issue by stayineverywhere** [oss2024hnu/coursegraph-py#53]
전공 기초는 컴퓨터 공학과 학생이면 필수로 들어야 하는 과목이므로 전공기초인 과목은 표시를 해두고 분류를 하거나 색상을 표기하거나 ce.yaml에 수정하면 좋을 것 같습니다.

**Comment by stayineverywhere** [comment]
ce.yaml에는 추가를 하였습니다.

**Comment by stayineverywhere** [comment]
#91 에서 말한 표시 관련해서는 고민을 해보고 수정해보겠습니다.

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/113 로 해결됨
