### ISSUE TITLE
dot 생성시 숨기려는 노드/링크를 흰색으로 처리하면 배경색이 달라졌을 때 보이는 문제

### ISSUE THREAD

**Issue by kyagrd** [oss2024hnu/coursegraph-py#530]
선수과목 의존성이 없는 경우에도 생성되는 그래프에서 학기간 순서를 어느 정도 맞추기 위해
처음에는 디버깅용으로 점선으로 임시로 그리던 보이지 않는 노드/에지를 이제는
현재 2a82460b1febe365f35d09b2c956f5f68765921c 버전의 `show_dot.py`에서아래처럼 흰색으로 하여 배경색과 같아져서 보이지 않게 하고 있습니다.

```
    graph.styleAppend("dashed", "color", "White")
    graph.styleAppend("dashed", "style", "dashed")
```

하지만 이런 방법은 배경색이 흰색이 아닌 경우에는 또 드러나 보이게 됩니다.

이 문제를 해결하려면 색상을 지정하는 것이 아니라 배경색에 관계없이 보이지 않는 스타일 속성으로 처리해야 합니다.

참고: https://graphviz.org/docs/attr-types/style/

**Comment by leesang01** [comment]
#542에서 pr하였습니다.
