### ISSUE TITLE
show_graph.py의 데이터 구조와 접근사

### ISSUE THREAD

**Issue by awc0596** [oss2024hnu/coursegraph-py#533]
subjects['학년']과 같은 직접적인 접근 방식은 데이터 구조의 변경에 취약합니다. 이를 개선하기 위해 몇 가지 방안을 제안하겠습니다.
데이터 접근을 위한 함수를 수정하는 방법을 선택했습니다.
def draw_course_structure -----부분을 수정하면 좋을것같습니다.
이 접근 방식을 통해 데이터 구조의 변경이 있을 떄 'SubjectData' 클래스 내부의 구현만을 수정하여 전체 애플리케이션에 대한 변경사항을 쉽게 관리할 수 있을것입니다.

**Comment by kyagrd** [comment]
이건 반려합니다. 데이터 형식은 확정해 놓고 스키바 체커까지 쓰면서 검사합니다. 적절치 않고 코드의 복잡성만 더하는 내용입니다. 지금으로선
