### ISSUE TITLE
show_dot.py 에서 과목과 노드의 키 초기화시 (학년,학기)구조 반복

### ISSUE THREAD

**Issue by Jokeongmin** [oss2024hnu/coursegraph-py#534]
subGdict와 nodedict 초기화에서 키로 사용되는 (학년, 학기) 구조가 반복되는데 이를 간소화 하여 재구성 한다면 코드의 효율성이 올라갈것 같습니다.

**Comment by kyagrd** [comment]
키의 종류가 같은 두 딕셔너리가 있다고 해서 재구성하면 무조건 코드의 효율성이 올라가지 않거든요?
그러니까 어떤 경우에 올라갈 거 같은지 시나리오나 구체적인 아이디어나 직관을 제시하지 않았으므로 반려합니다.

너무 추상적이고 될지 안될지 몰라요.

그냥 단순히 두 딕셔너리 합쳐서 한 딕셔너리로 만든다 설머 이건 아니겠죠?

**Comment by kyagrd** [comment]
제가 만든 게 최선의 코드라는 게 아니라 "간소화해서 재구성"이라는 게 너무 추상적이고 "코드의 효율이 올라간다"는 거에 대한 인과관계는 또 논리적으로 근거나 힌트나 아이디어나 가능성이 제시되지 않고요

**Comment by Jokeongmin** [comment]
다시 고민해보겠습니다
