### ISSUE TITLE
show_graph.py의 인터페이스의 명확성 부족

### ISSUE THREAD

**Issue by awc0596** [oss2024hnu/coursegraph-py#543]
일부 함수들이 반환 값을 제대로 문서화하고 있지 않습니다. 예를 들어, draw_course_structure 함수는 리턴값에 대한 설명이 부족합니다. 
인터페이스의 명확성 부족은 코드를 사용하는 다른 개발자나 미래의 유지보수 작업에 혼란을 줄 수 있습니다.

**Comment by kyagrd** [comment]
인터페이스 설계가 문제라는 건가요 문서가 문제라는 건가요? 뜻이 정확히 전달되게 이슈 다시 작성해 주세요.

문서화를 해달라는 건지 문서화 말고 소스코드 구조를 바꾸자는 건지 ...
