### ISSUE TITLE
show_dot.py 파일 내 validate_subject 함수의 유효성 검사 필요

### ISSUE THREAD

**Issue by peyoon** [oss2024hnu/coursegraph-py#550]
현재 validate_subject 함수는 '학년'과 '학기' 값이 숫자인지(isdigit())만 확인합니다. 그러나, 이 검사는 입력값이 음수이거나 0인 경우를 필터링하지 못합니다. 예를 들어, '-1'이나 '0' 또는 학년이 5 이상이거나 학기가 3 이상인 값이 통과될 수 있습니다.

학년과 학기의 값이 비정상적이면 나머지 코드에서도 잘못된 데이터를 처리하게 되어 프로그램의 동작에 문제가 발생할 수 있습니다. 예를 들어, 그래프를 그릴 때 비정상적인 학년 및 학기 값으로 인해 올바르지 않은 결과를 출력하거나 오류를 발생시킬 수 있습니다.
이런 부분에서 개선이 필요하다고 봅니다

**Comment by kyagrd** [comment]
validate subject가 애초에 불필요한 함수입니다. 그래서 이 이슈는 반려합니다.
