### ISSUE TITLE
show_dot.py 오류 추적

### ISSUE THREAD

**Issue by leesang01** [oss2024hnu/coursegraph-py#554]
에러 메시지에 예외 타입과 설명 포함

Python에서 예외가 발생하면, 예외의 이름과 발생 원인을 함께 출력하도록 설정할 수 있습니다. 이를 위해 try-except 블록을 사용하고, 발생한 예외를 캡처하여 메시지와 함께 출력합니다. 

Python에서 제공하는 logging 모듈을 활용하여 로그를 기록할 수 있습니다. 이 모듈은 다양한 로그 레벨(INFO, DEBUG, WARNING, ERROR, CRITICAL)을 제공하며, 로그 메시지를 콘솔, 파일, 네트워크 등 다양한 출력 대상으로 전송할 수 있습니다.

**Comment by kyagrd** [comment]
이런 것도 좋지만 테스트를 확실히 하고 제출해 주세요

**Comment by kyagrd** [comment]
그리고 이미 로그 이야기 나와서 중복이에요 예외처리 같은 건 너무 일반적인 이야기고 비슷한 이야기 전에도 나왔고 이미 일부 예외처리된 곳도 있는데 예외처리가 부족한 곳이 있다면 어떤 곳인지 구체적인 정보를 이야기해야지

이런 두루뭉실한 이야기는 이슈로 적절치 않습니다. 이전 이슈와 중복된 내용도 있고
