### ISSUE TITLE
데이터 파일의 정확한 구조 명세/검사를 위한 스키마가 필요해 보입니다.

### ISSUE THREAD

**Issue by JWhyeok** [oss2024hnu/coursegraph-py#56]
앞으로 사용할 데이터의 형식을 지정하는 문서와 

데이터 변경시 우리가 정한 형식에 맞게 검수할 수 있는 스키마가 필요할 것 같습니다.

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/121 을 머지함으로써 해결
