### ISSUE TITLE
schema_checker.py에서 구체적인 예외처리

### ISSUE THREAD

**Issue by seonghun0825** [oss2024hnu/coursegraph-py#565]
예외 처리에서 특정 오류를 구체적으로 잡아내는 것이 좋을 것 같습니다. 

FileNotFoundError, YAMLValidationError, ValueError 등을 
각각 다르게 처리하면 어떤 부분에서 문제가 발생했는지 명확히 알 수 있습니다.

**Comment by kyagrd** [comment]
아니 뭘 어떻게 구체적인가요 이게 ... 어느 부분의 코드에서 오류가 날 거 같다는 이야기도 없고 이러지 맙시다 제발
어떻게 다르다는 이야기도 없고
이거 보고 누가 어 어떤 걸 고쳐야 되겠다는 감이 저도 안오는데
누가 알아들으라고 이슈를 올리는 건가요?
