### ISSUE TITLE
작업이 장기적일 때 진행 상황 보고

### ISSUE THREAD

**Issue by jyh0** [oss2024hnu/coursegraph-py#567]
완료하는 데 다소 시간이 걸릴 수 있는 작업에 대한 진행률 표시기 또는 상태 업데이트를 구현합니다. 이를 통해 사용자는 스크립트가 활발하게 작동하고 있음을 확신하고 현재 상태를 알 수 있으면 좋겠습니다.

**Comment by kyagrd** [comment]
이런 맥락없고 구체성 없는 이슈는 받지 않습니다.
