### ISSUE TITLE
gui.py 코드 구조화

### ISSUE THREAD

**Issue by awc0596** [oss2024hnu/coursegraph-py#568]
코드가 한 클래스 내에 너무 많은 기능을 포함하고 있어 가독성과 유지보수가 어렵습니다. 파일처리 이미지 처리 등의 기능을 별도의 클래스나 모듈로 분리하는것이 좋을거같습니다.

**Comment by kyagrd** [comment]
이런 추상적 이슈 마지막에 던지는 거 좋지 않아요 받지 않습니다.
