### ISSUE TITLE
에러 핸들링 추가 

### ISSUE THREAD

**Issue by ychankk** [oss2024hnu/coursegraph-py#58]
파일 입출력을 수행할 때 파일이 없거나 접근할 수 없는 등의 경우에 대비하기 위해서 추가 해야될 거 같습니다.

**Comment by kyahnu** [comment]
지금 이제 ai-concept-demo에서 작업은 그만하기로 했습니다.
그러니까 이거는 __main__.py가 있는 coursegraph 디렉토리로 지금 옮기고 있는데 옮겨진 코드에서도 같은 문제가 있으면 그때 다시 무슨 파일에 어떤 문제를 개선해야 한다고 상세한 정보와 함께 이슈를 제기해 주세요
이 이슈는 일단 반려합니다.
