### ISSUE TITLE
모듈 임포트 최적화.

### ISSUE THREAD

**Issue by awc0596** [oss2024hnu/coursegraph-py#59]
사용하지 않는 'fntutil' 모듈을 제거하면 좋을거 같습니다. 필요하지 않은 묘듈을 임포트하는 것은 프로그램의 로딩 시간에 영향을 줄 수 있으며,  의존성 관리를 더 복잡하게 만드는 요소인거 같습니다.

**Comment by awc0596** [comment]
'fontutil'입니다

**Comment by kyahnu** [comment]
앞으로 사용할 거라서 일부러 만들어 놓은거에요. 일단 빈 파일부터 만들어 놓고 작업하라고요. 이슈거리가 아닙니다.
