### ISSUE TITLE
일반 yaml 대신 strictyaml로 바꿔주세요

### ISSUE THREAD

**Issue by kyagrd** [oss2024hnu/coursegraph-py#6]
우리가 작성하고자 하는 과목 데이터는 간단한 형식이라서
YAML의 모든 복잡한 기능이 필요가 없으니
스키마 작성과 검사가 좀더 간단한 StrictYAML을 활용하도록
라이브러리를 교체하면 좋을 것 같습니다.

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/9 해결됨
