### ISSUE TITLE
다이얼로그박스에서 재실행 가능하게 해야합니다.

### ISSUE THREAD

**Issue by eongeung** [oss2024hnu/coursegraph-py#60]
다이얼로그박스를 한번 보고 나면 다시 띄우기 위해서 프로그램을 재실행해야되는데, 이를 개선하기 위해서 다중 인스턴스를 관리할 수 있는 기능을 추가하여, 사용자가 다중 다이얼로그박스를 열고 필요에 따라 닫을 수 있도록 해야 합니다.

**Comment by kyahnu** [comment]
CLI유틸리티를 여러 번 실행하는 건 쉘스크립트를 통해서 하는 일이지 보통 CLI 유틸리티 자체에 포함되는 기능이 아닙니다.

CLI유틸리티를 기반으로 하는 GUI를 아예 따로 만드는 설계를 해서 진행한다면 모를까 이는 지금 CLI 프로그램을 작성하는 맥락에는 맞지 않으므로 반려합니다.

진짜 GUI를 만들고 싶다면 어떤 UX로 만들지 어느 정도 구체적인 구상을 가져와서 새로운 이슈를 제기해 주세요.

이렇게 한두 문장으로 추상적으로 이야기하면 다른 사람이 이 이슈를 보고 작업을 한다고 했을 때 막막하지 않을 정도의 이슈를 작성해 주세요 앞으로는 이슈를 올릴 때요
