### ISSUE TITLE
yaml 스키마를 검증해야 합니다.

### ISSUE THREAD

**Issue by eongeung** [oss2024hnu/coursegraph-py#61]
입력받는 yaml 파일이 특정 스키마를 준수하고 있는지 검증할 수 있는 기능을 추가해야합니다. 예를 들어 python 의 'pykwalify'같은 라이브러리를 사용할 수 있습니다.

**Comment by kyahnu** [comment]
중복 이슈 좀전에 누가 올렸습니다
