### ISSUE TITLE
추가 기능이 부족합니다.

### ISSUE THREAD

**Issue by peyoon** [oss2024hnu/coursegraph-py#63]
# Add more functionality based on your application needs를 추가하였지만, 현재의 스크립트는 매우 기본적인 기능만을 제공합니다. 실제 유용한 명령줄 도구가 되려면 특정 데이터 처리나 변환 기능을 구현할 필요가 있습니다.

**Comment by kyahnu** [comment]
지나치게 일반적이고 추상적인 이슈는 부적절합니다. 닫습니다.
