### ISSUE TITLE
파일이 존재하는지와 접근성 검사를 해야합니다.

### ISSUE THREAD

**Issue by eongeung** [oss2024hnu/coursegraph-py#65]
Python의 os.path.exists() 및 os.access() 함수를 사용하여 파일이 존재하고 읽기/쓰기가 가능한지 확인해야합니다.

**Comment by kyahnu** [comment]
ai-concept-demo에 있는 세부적인 코드에 대한 이슈는 받지 않습니다. 왜냐하면 일단 지금은 __main__.py가 있는 쪽으로 코드를 다시 정리하고 있잖아요. 거기서도 같은 문제가 있으면 그때 다시 이슈를 제기해 주세요. 일단은 반려합니다. 그리고 혹시 다음이 이런 이슈를 제기할 경우 구체적으로 어느 코드 파일의 어느 부분이 문제라고 제기 바랍니다.
