### ISSUE TITLE
concept-demo.py에서 macOS의 폰트 설정이 잘못되어 있는것 같습니다.

### ISSUE THREAD

**Issue by ppoppy** [oss2024hnu/coursegraph-py#68]
실행 테스트를 하기 위해 concept-demo.py 실행했더니 폰트를 찾을 수 없다는 에러가 발생하였습니다.
다른 macOS를 쓰는 학생들이 테스트를 수월하게 하기 위해 수정이 필요해 보입니다.

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/73 이걸로 일단은 수정사항이 포함된 거 같습니다
