### ISSUE TITLE
로깅 추가

### ISSUE THREAD

**Issue by leesang01** [oss2024hnu/coursegraph-py#69]
프로그램의 실행 과정을 기록하고 추적할 수 있도록 로깅을 추가하는 것이 유용합니다. logging 모듈을 사용하여 로그를 기록하고 수준을 지정하여 필요한 만큼의 상세함으로 로그를 남길 수 있습니다.

**Comment by kyahnu** [comment]
지나치게 추상적인 이슈이므로 지금 단계에서는 부적절합니다.

아직 무슨 서버를 만든 것도 아니잖아요 CLI 유틸리티 만들고 있는데.

오래 계속 도는 서버나 서버가 아니라도 굉장히 오래 걸리는 시뮬레이션 프로그램이나 그런 데 로그가 필요하죠.

이정도 간단한 유틸리티는 디버거로도 충분합니다.

일반적으로 있으면 좋다 수준의 지나치게 추상적이고 일반적인 이슈이므로 현재 프로젝트와 부적절하여 반려하고 닫습니다.
