### ISSUE TITLE
main 파일에서 프린트문 이슈를 제기합니다.

### ISSUE THREAD

**Issue by peyoon** [oss2024hnu/coursegraph-py#71]
if output_file:
        print(f"Output file path: {output_file}")

    if input_file:
        print(f"Output file path: {output_file}")
        
이 부분에서 input_file을 확인할 때 사용된 프린트 문에서 "Output file path:"라고 잘못 기재되어 있습니다. 이는 input_file의 경로를 출력해야 함에도 불구하고 output_file의 경로를 출력하도록 되어 있어 혼란을 줄 수 있습니다.

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/73 로 해결
