### ISSUE TITLE
열 너비 조정

### ISSUE THREAD

**Issue by m222zu** [oss2024hnu/coursegraph-py#72]
ax.table에서 colWidths를 모든 열에 대해 동일하게 설정했지만, 내용에 따라 열 너비를 조정하는 것이 필요해보입니다.
예를 들어, 과목명 열은 다른 열보다 더 넓게 설정하는 것처럼 말입니다

**Comment by kyahnu** [comment]
무슨 파일의 어디인지 본인이 아닌 다른 사람도 알아볼 수 있게 작성해 주세요.

**Comment by kyahnu** [comment]
어떤 버전의 무슨 파일의 어느 곳에서 이슈가 있는지 상세한 정보를 제공 바랍니다 이런 식이면 다른 사람들이 뭐가 문제인지 맥락이 없어서 알기 어렵습니다. 그리고 ai-concept-demo 에는 이제 작업을 중지하므로 __main__.py 쪽 디렉토리로 기능이 옮겨온 다음에도 같은 문제가 계속 있으면 그때 이슈를 다시 제기해 주시기 바랍니다. 좀더 구체적으로 다른 사람도 무엇이 문제인지 충분히 알 수 있도록 정보들을 포함해서요.

**Comment by kyahnu** [comment]
일단은 이 이슈는 반려합니다
