### ISSUE TITLE
그래픽 출력의 세부 조정  (('ax')의 불필요)

### ISSUE THREAD

**Issue by awc0596** [oss2024hnu/coursegraph-py#75]
표를 보여주는 동안 축('ax')가 굳이 필요하지 않으므로,
'ax.axis('off')'로 설정하여 축을 완전히 숨기는것이 좋을거 같습니다.
'ax.axis('tight')는 제거해도 될거같습니다.

**Comment by kyahnu** [comment]
이슈를 올릴 때는 다른 사람들도 알아볼 수 있게 최소한 무슨 파일의 내용인지라도 최소한의 친절한 정보를 제공합시다

**Comment by kyahnu** [comment]
지금 __main__.py 쪽으로 옮기고 있으니 코드 세부사항에 대한 이슈는 일단 반려하고 옮겨진 코드에도 같은 문제가 있으면 그때 이슈를 다시 제기해 주세요
