### ISSUE TITLE
보고서 생성 기능을 추가하면 좋을 것 같습니다.

### ISSUE THREAD

**Issue by Jae20230112** [oss2024hnu/coursegraph-py#77]
데이터 분석 결과를 자동으로 보고서 형태로 생성하는 기능을 구현하는 방식을 추가하면 결과를 한눈에 보기 쉬울 것 같습니다.
jupyter notebook을 이용해서 html, pdf등을 파일로 내보내거나 파이썬 ReportLab 라이브러리로 PDF 문서를 생성할 수 있을 것 같습니다

**Comment by kyahnu** [comment]
??? 지금 무슨 거창한 데이터를 분석하는 게 아닌데요 ... 그림을 하나 만들어내는 거지
프로젝트의 현재 상태나 내용과 좀 동떨어진 맥락에 맞지 않은 지나치게 일반적이고 추상적인 내용이므로 부적절한 이슈로 판단하여 닫음
