### ISSUE TITLE
__main__.py 코드의 간결성 관련

### ISSUE THREAD

**Issue by shofjablas** [oss2024hnu/coursegraph-py#78]
# Adding command line options
11번 줄 '--input', 12번줄 '--ouput', 13번줄 '--verse'에서 코드 간결성을 위해 11번 줄 '-input', 12번줄 '-ouput', 13번줄 '-verse'에서 수정하는게 좋을거같습니다.

**Comment by kyahnu** [comment]
옵션 라이브러리를 아직 이해하지 못하는, 그게 아니라 -와 --를 보통 쓰는 용도를 이해하지 못해서 오해로 인한 부적절한 이슈입니다. 닫습니다.
