### ISSUE TITLE
--main--.py에서 아직 과목을 불러올 수 없습니다.

### ISSUE THREAD

**Issue by eongeung** [oss2024hnu/coursegraph-py#79]
데모처럼 과목을 불러올 수 있도록 해야 하는데, 추후 data 폴더를 연결하여 ce.yaml과 me.yaml을 한번에 같이 불러올 수 있도록 해야합니다.

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/issues/76 중복 이슈이므로 반려합니다
