### ISSUE TITLE
파일경로 설정이 잘못되었습니다.

### ISSUE THREAD

**Issue by SiRyung** [oss2024hnu/coursegraph-py#8]
font파일을 찾는 malgun.ttf파일의 경로설정이 잘못되어있습니다.
filename인 input.yaml파일의 경로설정이 잘못되어있습니다.

바로 pull requests에 참여하였습니다.

**Comment by kyahnu** [comment]
무조건 최상위 디렉토리에서 실행해야 한다는 가정을 해야 이게 잘못된 거고 수정이 필요한 거 같은데
그런 가정을 꼭 해야 하는 건 아니라고 보여서 ..
이 이슈는 일단 여기서 닫기로 하겠습니다.
