### ISSUE TITLE
플랫폼별 폰트 처리

### ISSUE THREAD

**Issue by eunzzu** [oss2024hnu/coursegraph-py#81]
시스템별 폰트 처리 방식을 더욱 견고하게 만들어야 할 것 같습니다. 사용 가능한 폰트를 확인하거나 다양한 운영 시스템에서 기본 폰트를 지정하는 더 안정적인 방법을 사용하면 좋을 것 같습니다..

**Comment by kyahnu** [comment]
이미 논의되고 있는 중복된 이슝를 계속 중복해서 올리지 맙시다.
