### ISSUE TITLE
폰트 모듈 필요

### ISSUE THREAD

**Issue by yjs02330** [oss2024hnu/coursegraph-py#82]
main.py 도 concept-demo.py , matplotlib를 이용이유로 한글 깨짐 문제로 시스템 폰트를 사용해 설정할 필요가 있습니다.

import matplotlib.pyplot as plt
from matplotlib import font_manager, rc
font_path : 기본글꼴 경로

**Comment by yjs02330** [comment]
글꼴 경로 또한 사람마다 다를수 있기에 경로를 자동으로 탐색하거나 검색할 수 있는 방안이 필요합니다.

**Comment by kyahnu** [comment]
이미 논의도괴 있는 중복된 이슈입니다. 닫습니다.
