### ISSUE TITLE
폰트 경로 하드코딩 문제

### ISSUE THREAD

**Issue by eunzzu** [oss2024hnu/coursegraph-py#84]
Linux에서 폰트 경로를 하드코딩하는 것은 권장되지 않습니다. 배포판에 따라 폰트 경로가 다를 수 있기 때문에 더 유연한 접근 방법이 필요합니다. 사용자가 폰트 경로를 입력할 수 있도록 하거나, 기본적으로 설치되어 있는 폰트를 자동으로 탐색하도록 변경할 필요가 있습니다.

**Comment by kyahnu** [comment]
이미 다른 이슈에서 논의되고 있습니다. 중복된 이슈 올리지 말아주세요
