### ISSUE TITLE
과목명이 길어지면 원 안에 다 들어가지 않습니다.

### ISSUE THREAD

**Issue by ppoppy** [oss2024hnu/coursegraph-py#89]
원은 가로로 넓히면 모양이 이상해지니, 직사각형 모양으로 바꾸어 과목명을 나타내는 것이 좋아 보입니다.

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/issues/16 와 중복이므로 부적절한 이슈, 반려
