### ISSUE TITLE
전공 필수, 전공 선택, 전공 기초 표시 관련

### ISSUE THREAD

**Issue by shofjablas** [oss2024hnu/coursegraph-py#91]
![image](https://github.com/oss2024hnu/coursegraph-py/assets/97035336/43da8ea6-5dd5-4408-b7a7-96de5e0e3ed8)이런식으로 각각 윤곽선을 나타내면 좋을거같습니다.

**Comment by kyahnu** [comment]
겹치는 내용이 있는 이슈는 새로 만들지 말고 이미 올라온 관련 주제 이슈에서

https://github.com/oss2024hnu/coursegraph-py/issues/53

 댓글을 통한 토론으로 다뤄주시기 바랍니다.

이 이슈는 반려하고 닫습니다.
