### ISSUE TITLE
2학기가 위에 1학기가 아래에 배치되고 있는 문제점 해결을 위해 상하 위치를 바꿀 필요

### ISSUE THREAD

**Issue by KimDongYeun** [oss2024hnu/coursegraph-py#94]
상단에는 2학기 강의가 하단에는 1학기 강의가 출력됩니다. 상단에는 1학기 강의, 하단에는 2학기 강의가 출력되도록 바꿔야할 것 같습니다.

**Comment by kyahnu** [comment]
이거 이미 논의 되었어요 중복된 이슈 올리지 말아주세요. 인터넷에 과목이수체계도는 대부분 학년에 따라 가로입니다.

**Comment by kyahnu** [comment]
이미 관련 이슈가 있으면 거기서 논의를 해주세요 새로 이슈 만들지 말고.

2학기와 1학기가 상단 하단이 바뀌어서 출력되고 있는지는 처음 지적된 거 같으니까 이슈 제목을 그걸로 바꾸겠습니다.

**Comment by KimDongYeun** [comment]
넵 수정했습니다. 관련사항은 겹치는 노드 이슈에 남겨놓겠습니다.
