### ISSUE TITLE
실습, 학점 추가했으면 좋겠습니다.

### ISSUE THREAD

**Issue by eongeung** [oss2024hnu/coursegraph-py#95]
__main__.py에서 학년, 학기, 과목명, 트랙만 나와있기 때문에 실습유무와 학점을 추가하여 더 자세히 볼 수 있으면 좋을 것 같습니다.

**Comment by kyahnu** [comment]
입력형식에 중복된 이슈 실습유무 관련 이슈 등 다른 이슈에서 이미 논의가 진행되고 있는 중복된 내용입니다 기존 이슈와 PR의 내용읊 파악하고 올려주세요. 이건 반려하고 그냥 닫습니다.
