### ISSUE TITLE
demo에서 시각화 화살표 문제

### ISSUE THREAD

**Issue by eongeung** [oss2024hnu/coursegraph-py#96]
4학년 1학기에 이수해야 하는 컴퓨터과학의 선수과목이 수학, 물리학으로 되어있는데 시각화된 figure을 보면 수학->물리학->컴퓨터과학 식으로 되어있어 데이터와 맞지 않습니다.

**Comment by kyahnu** [comment]
transitive 한 것은 당연히 표기하지 않습니다. 부적절한 이슈. 이미 똑같은 내용으로 올렸다가 반려한 이슈가 있습니다. 지금까지 올라온 이슈와 중복되지 않는지 확인하고 이슈를 올려주세요.
