### ISSUE TITLE
시각화 그림 가독성이 떨어집니다

### ISSUE THREAD

**Issue by eongeung** [oss2024hnu/coursegraph-py#97]
1-2 2-2 3-2 4-2
1-1 2-1 3-1 4-1 식으로 되어있어 가독성이 떨어집니다.
1-1 1-2
2-1 2-2
3-1 3-2
4-1 4-2 식으로 되어있으면 보기 편할 것 같습니다.

**Comment by kyahnu** [comment]
인터넷에 과목이수체계도 검색해보면 가로가 훨씬 많고 표준적이라 가로로 하기로 이미 논의도었습니다. 지금까지 이슈들 진행상황을 확인하고 올려주세요. 이전에도 반려했던 중복 이슈이므로 닫습니다.

**Comment by eongeung** [comment]
그럼 

1-2 2-2 3-2 4-2
1-1 2-1 3-1 4-1  처음에 이렇게 되어있었는데, 2학기가 위에 있는 것이 가독성이 떨어져

1-1 1-2 2-1 2-2 3-1 3-2 4-1 4-2 이런 식 혹은 1학기와 2학기의 위치를 바꿔서 다시 올려도 괜찮을까요?
