### ISSUE TITLE
화살표 색깔 구분

### ISSUE THREAD

**Issue by eongeung** [oss2024hnu/coursegraph-py#98]
고학년으로 갈 수록, 웹/앱, 빅데이터인공지능, 백엔드, 정보보안을 세세하게 배우게 됩니다. 예를 들어 정보보호개론에서 시스템보안으로 가게 되고, 웹스크립트프로그래밍에서 웹서버 프로그래밍으로 가게 되는데, 이런 선수과목 화살표를 분야별로 다른 색깔로 지정했으면 좋겠습니다.

**Comment by kyahnu** [comment]
색상에 대한 논의도 이미 다른 이슈에서 논의가 진행되고 있죠 중복된 이슈입니다.
