### ISSUE TITLE
노드에서 학강실 표시

### ISSUE THREAD

**Issue by stayineverywhere** [oss2024hnu/coursegraph-py#99]
노드의 경우에 학년과 학기만 나타나 있는데 과목을 볼때 학점,강의,실습도 중요하게 봤었고 시간표를 짤때 참고를 했었기에 과목 옆에 학강실 예로 3-3-0 이런식으로 아니면 3/3/0 이렇게 나타내도록 보완하면 좋을 것 같습니다.

**Comment by kyahnu** [comment]
https://github.com/oss2024hnu/coursegraph-py/pull/128 이 이슈로 내용이 추가가 되기는 했는데

아쉬운 점은 학/강/실 키에 대한 value 형식이 저렇게 되면 그냥 아마 string이라서 중간에 빈칸 있는 ... 

좀더 프로그램에서 처리하기 편리한 형식으로 다음을 참고해서 
https://hitchdev.com/strictyaml/using/alpha/compound/fixed-length-sequences/
개선하는 것이 좋을 것 같습니다.

추가 PR을 넣을 거리라는 말이죠 :)

**Comment by kyagrd** [comment]
> #178 소스코드로 수정하였습니다. 데이터 프레임을 만들때 공백을 없애는 방식으로 개선하였습니다.

공백을 없애라는 것이 아니라 이게 내용상 리스트가 맞기 때문에 리스트로 바꾸자는 것이었습니다.

```
학/강/실:
  - 3
  - 3
  - 0
````
이런 식으로요.

**Comment by kyagrd** [comment]
왜냐하면 학/강/실 이라는 거는 3개의 정수 데이터잖아요 그 의미가. 문자열이 아니잖아요 직관적으로.
데이터 형식 자체를 프로그램에서 처리하기 가장 자연스러운 형식으로 해 놓는 게 좋지, 문자열을 억지로 수로 변환하는 것은 프로그램만 복잡하게 만들죠. 스키마에서 그냥 처리되게 만드는 것이 가장 좋습니다.

사람이 입력하기 불편한 것이 걱정이라면 그거는 yaml 파일에서 해결할 문제가 아니고 UI가 편리한 에디터를 만드는 것으로 해결할 문제입니다.

yaml은 데이터 형식을 표현하기 위한 것이 일차적인 목적이지 사람이 작성하기 편한 UI로서의 기능은 부차적인 목표죠.

**Comment by stayineverywhere** [comment]
데이터 형식을 리스트로 바꾸었습니다!!
